# Generated by Django 4.2.29 on 2026-04-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='follow',
            new_name='social_foll_followe_0eabb0_idx',
            old_name='social_foll_followee_idx',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('follower', models.F('followee')), _negated=True), name='social_follow_no_self_follow'),
        ),
    ]
