# Generated by Django 4.2.29 on 2026-05-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_phase13_extension'),
        ('profiles', '0002_alter_officeprojectlink_confidence'),
        ('social', '0003_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='profiles.office')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_following_set', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['followee', '-created_at'], name='social_offi_followe_33658e_idx')],
                'unique_together': {('follower', 'followee')},
            },
        ),
    ]
