# Generated by Django 4.2.30 on 2026-06-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_liked_building_ids'),
        ('social', '0004_officefollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architect_id', models.TextField(db_index=True)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architect_following_set', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['follower', '-followed_at'], name='social_arch_followe_6c1ec7_idx')],
                'unique_together': {('follower', 'architect_id')},
            },
        ),
    ]
