# Generated by Django 4.2.29 on 2026-06-04 08:00
# + hand-added RunPython (ARCHITECT-UNIFY-C): reset the now-orphaned
#   profiles.Office.follower_count, since OfficeFollow's counter-cache signal
#   writer is deleted with the model (Codex review #190).

from django.db import migrations


def _reset_office_follower_count(apps, schema_editor):
    """Dropping OfficeFollow also drops its post_save/post_delete signals that
    maintained profiles.Office.follower_count. Any prod rows would leave that
    denormalized counter frozen at a stale value. No office-follow mechanism
    remains (ArchitectFollow is the live follow path), so the correct value is 0.
    """
    Office = apps.get_model('profiles', 'Office')
    Office.objects.update(follower_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_architectfollow'),
        # RunPython touches profiles.Office (follower_count) → ensure profiles is
        # fully migrated first.
        ('profiles', '0005_delete_savedoffice'),
    ]

    operations = [
        migrations.RunPython(_reset_office_follower_count, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='OfficeFollow',
        ),
    ]
