# Generated by Django 4.2.29 on 2026-06-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_architectfollow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeFollow',
        ),
    ]
