# Generated by Django 4.2.30 on 2026-06-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_delete_officefollow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
