# Generated by Django 4.2.30 on 2026-07-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_login_onboard_1_unified_id_and_is_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reaction', 'Reaction'), ('password_changed', 'Password Changed'), ('new_login', 'New Login')], max_length=20)),
                ('category', models.CharField(choices=[('social', 'Social'), ('security', 'Security')], max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.userprofile')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notif_recip_created_idx'), models.Index(fields=['recipient', 'read_at'], name='notif_recip_readat_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnownDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_devices', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('user', 'ua_hash')},
            },
        ),
    ]
