# Generated by Django 4.2.29 on 2026-04-29 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('aliases', models.JSONField(default=list)),
                ('verified', models.BooleanField(default=False)),
                ('claim_status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unclaimed', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('canonical_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeProjectLink',
            fields=[
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building_id', models.TextField(db_index=True)),
                ('confidence', models.FloatField()),
                ('source', models.CharField(choices=[('manual', 'Manual Claim'), ('canonical_fk', 'Canonical FK'), ('string_match', 'String Match'), ('admin_assigned', 'Admin Assigned')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='profiles.office')),
            ],
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['name'], name='profiles_of_name_f26644_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['claim_status'], name='profiles_of_claim_s_55cae1_idx'),
        ),
        migrations.AddIndex(
            model_name='officeprojectlink',
            index=models.Index(fields=['building_id'], name='profiles_of_buildin_cd1dab_idx'),
        ),
        migrations.AddIndex(
            model_name='officeprojectlink',
            index=models.Index(fields=['source'], name='profiles_of_source_8d42d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='officeprojectlink',
            unique_together={('office', 'building_id')},
        ),
    ]
