# Generated by Django 4.2.30 on 2026-06-02 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_alter_officeprojectlink_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_recommendable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office',
            name='primary_city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='primary_country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='canonical_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='SavedOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='profiles.office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_offices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'office')},
            },
        ),
    ]
