# Generated by Django 4.2.30 on 2026-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_office_is_recommendable_office_primary_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='canonical_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
