# Generated by Django 4.2.29 on 2026-06-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_office_canonical_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedOffice',
        ),
    ]
