# Generated by Django 4.2.30 on 2026-10-02 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_personalityprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('a_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('b_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_a', to='accounts.userprofile')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_b', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'User'), ('message', 'Message'), ('profile', 'Profile')], max_length=10)),
                ('target_id', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ignored', 'Ignored')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_contact_requests', to='accounts.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_contact_requests', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='accounts.userprofile')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', max_length=10)),
                ('system_type', models.CharField(blank=True, default='', max_length=20)),
                ('body', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'id'], name='message_conv_id_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='uniq_conversation_pair'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(('user_a__lt', models.F('user_b'))), name='conversation_pair_normalized'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['recipient', 'status'], name='contactreq_rcpt_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'recipient'), name='uniq_pending_contact_request'),
        ),
        migrations.AddConstraint(
            model_name='contactrequest',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('recipient')), _negated=True), name='contact_request_not_self'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='uniq_block_pair'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.CheckConstraint(check=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_not_self'),
        ),
    ]
