# Generated by Django 5.2.18 on 2026-10-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=120)),
                ('organizer_type', models.CharField(choices=[('public_agency', 'public_agency'), ('association', 'association'), ('local_gov', 'local_gov'), ('private_group', 'private_group'), ('unknown', 'unknown')], default='unknown', max_length=20)),
                ('submission_deadline', models.DateTimeField(db_index=True)),
                ('apply_deadline', models.DateTimeField(blank=True, null=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('eligibility', models.CharField(blank=True, max_length=120)),
                ('team_size', models.CharField(blank=True, max_length=60, null=True)),
                ('source_url', models.URLField(max_length=500)),
                ('listing_source', models.CharField(blank=True, max_length=40)),
                ('listing_url', models.URLField(blank=True, max_length=500)),
                ('poster_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('poster_credit', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('published', 'published'), ('hidden', 'hidden'), ('pending', 'pending')], db_index=True, default='hidden', max_length=10)),
                ('interest_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['submission_deadline'],
                'indexes': [models.Index(fields=['status', 'submission_deadline'], name='contest_status_deadline_idx')],
            },
        ),
    ]
