# Generated by Django 5.2.18 on 2026-10-10 15:18

import apps.contests.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_personalityprofile'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='listing_url',
            field=models.URLField(blank=True, max_length=500, validators=[apps.contests.validators.validate_http_url]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='poster_url',
            field=models.URLField(blank=True, max_length=1000, null=True, validators=[apps.contests.validators.validate_poster_url]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='source_url',
            field=models.URLField(max_length=500, validators=[apps.contests.validators.validate_http_url]),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.CheckConstraint(condition=models.Q(('source_url__iregex', '^https?://')), name='contest_source_url_http'),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.CheckConstraint(condition=models.Q(('listing_url', ''), ('listing_url__iregex', '^https?://'), _connector='OR'), name='contest_listing_url_http'),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.CheckConstraint(condition=models.Q(('poster_url__isnull', True), ('poster_url', ''), ('poster_url__iregex', '^https?://'), _connector='OR'), name='contest_poster_url_http'),
        ),
        migrations.AddField(
            model_name='contestinterest',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_interests', to='accounts.userprofile'),
        ),
        migrations.AddIndex(
            model_name='contestinterest',
            index=models.Index(fields=['contest', '-created_at'], name='contest_int_contest_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestinterest',
            unique_together={('user', 'contest')},
        ),
    ]
