# Generated by Django 5.2.18 on 2026-10-10 14:08

import apps.contests.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_personalityprofile'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='poster_permission_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='poster_permission_basis',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contest',
            name='listing_url',
            field=models.URLField(blank=True, max_length=500, validators=[apps.contests.validators.validate_http_url]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='poster_url',
            field=models.URLField(blank=True, max_length=1000, null=True, validators=[apps.contests.validators.validate_http_url]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='source_url',
            field=models.URLField(max_length=500, validators=[apps.contests.validators.validate_http_url]),
        ),
        migrations.CreateModel(
            name='ContestPosterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_reports', to='contests.contest')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_poster_reports', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_interests', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['contest', '-created_at'], name='contest_int_contest_idx')],
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
