# Generated by Django 5.2.18 on 2026-10-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_personalityprofile'),
        ('contests', '0002_interest_report_poster_basis'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.CheckConstraint(condition=models.Q(('source_url__iregex', '^https?://')), name='contest_source_url_http'),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.CheckConstraint(condition=models.Q(('listing_url', ''), ('listing_url__iregex', '^https?://'), _connector='OR'), name='contest_listing_url_http'),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.CheckConstraint(condition=models.Q(('poster_url__isnull', True), ('poster_url', ''), ('poster_url__iregex', '^https?://'), _connector='OR'), name='contest_poster_url_http'),
        ),
        migrations.AddConstraint(
            model_name='contestposterreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('contest', 'reporter'), name='contest_poster_report_once'),
        ),
    ]
