# Generated by Django 4.2.29 on 2026-03-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='initial_batch',
            field=models.JSONField(default=list),
        ),
    ]
