# Generated by Django 4.2.29 on 2026-04-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_analysissession_initial_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='convergence_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='like_vectors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='phase',
            field=models.CharField(choices=[('exploring', 'Exploring'), ('analyzing', 'Analyzing'), ('converged', 'Converged'), ('completed', 'Completed')], default='exploring', max_length=20),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='pool_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='previous_pref_vector',
            field=models.JSONField(default=list),
        ),
    ]
