# Generated by Django 4.2.29 on 2026-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_analysissession_convergence_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='pool_scores',
            field=models.JSONField(default=dict),
        ),
    ]
