# Generated by Django 4.2.29 on 2026-04-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_analysissession_pool_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
