# Generated by Django 4.2.29 on 2026-04-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_project_report_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='total_rounds',
        ),
        migrations.AlterField(
            model_name='swipeevent',
            name='idempotency_key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='swipeevent',
            unique_together={('session', 'idempotency_key')},
        ),
    ]
