# Generated by Django 4.2.29 on 2026-04-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('recommendation', '0008_analysissession_pool_relaxation_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_start', 'Session Start'), ('pool_creation', 'Pool Creation'), ('swipe', 'Swipe'), ('tag_answer', 'Tag Answer'), ('confidence_update', 'Confidence Update'), ('session_end', 'Session End'), ('session_extend', 'Session Extend'), ('bookmark', 'Bookmark'), ('detail_view', 'Detail View'), ('external_url_click', 'External URL Click'), ('failure', 'Failure'), ('probe_turn', 'Probe Turn'), ('cohort_assignment', 'Cohort Assignment')], db_index=True, max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('sequence_no', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recommendation.analysissession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_events', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'created_at'], name='recommendat_session_b72a70_idx'), models.Index(fields=['event_type', 'created_at'], name='recommendat_event_t_1c6aec_idx')],
            },
        ),
    ]
