# Generated by Django 4.2.29 on 2026-04-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_alter_sessionevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='v_initial',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionevent',
            name='event_type',
            field=models.CharField(choices=[('session_start', 'Session Start'), ('pool_creation', 'Pool Creation'), ('swipe', 'Swipe'), ('tag_answer', 'Tag Answer'), ('confidence_update', 'Confidence Update'), ('session_end', 'Session End'), ('session_extend', 'Session Extend'), ('bookmark', 'Bookmark'), ('detail_view', 'Detail View'), ('external_url_click', 'External URL Click'), ('failure', 'Failure'), ('probe_turn', 'Probe Turn'), ('cohort_assignment', 'Cohort Assignment'), ('parse_query_timing', 'Parse Query Timing'), ('hyde_call_timing', 'HyDE Call Timing')], db_index=True, max_length=32),
        ),
    ]
