# Generated by Django 4.2.29 on 2026-04-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0012_add_topic01_q_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='cosine_top10_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='dpp_top10_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='gemini_top10_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
