# Generated by Django 4.2.29 on 2026-05-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0016_alter_sessionevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='extended_rounds',
            field=models.IntegerField(default=0),
        ),
    ]
