# Generated by Django 4.2.30 on 2026-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0020_question_card_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAxisWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('axis', models.CharField(choices=[('form', 'form'), ('materiality', 'materiality'), ('scale', 'scale'), ('energy', 'energy'), ('tradition', 'tradition')], max_length=20)),
                ('weight', models.FloatField()),
            ],
            options={
                'unique_together': {('tag', 'axis')},
            },
        ),
    ]
