# Generated by Django 4.2.30 on 2026-06-04 12:28

import json
import os
from django.db import migrations, models


def _seed_tag_axis_weights(apps, schema_editor):
    TagAxisWeight = apps.get_model('recommendation', 'TagAxisWeight')
    fixture = os.path.join(
        os.path.dirname(__file__), '..', '..', '..', 'fixtures', 'tag_axis_weights.json'
    )
    with open(fixture, encoding='utf-8') as f:
        rows = json.load(f)
    for row in rows:
        fields = row['fields']
        TagAxisWeight.objects.update_or_create(
            tag=fields['tag'],
            axis=fields['axis'],
            defaults={'weight': fields['weight']},
        )


def _unseed_tag_axis_weights(apps, schema_editor):
    apps.get_model('recommendation', 'TagAxisWeight').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0020_question_card_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAxisWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('axis', models.CharField(choices=[('form', 'form'), ('materiality', 'materiality'), ('scale', 'scale'), ('energy', 'energy'), ('tradition', 'tradition')], max_length=20)),
                ('weight', models.FloatField()),
            ],
            options={
                'unique_together': {('tag', 'axis')},
            },
        ),
        migrations.AddConstraint(
            model_name='tagaxisweight',
            constraint=models.CheckConstraint(
                check=models.Q(weight__gte=-1.0) & models.Q(weight__lte=1.0),
                name='tagaxisweight_weight_range',
            ),
        ),
        migrations.RunPython(_seed_tag_axis_weights, _unseed_tag_axis_weights),
    ]
