# Generated by Django 4.2.29 on 2026-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0021_tagaxisweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='conversation_history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
