# Generated by Django 4.2.29 on 2026-06-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0023_project_report_image_mime'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='axis_scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
