# Generated by Django 4.2.29 on 2026-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0024_project_axis_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='multimodal_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
