# Generated by Django 4.2.30 on 2026-06-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0028_project_is_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='action_card_shown',
            field=models.BooleanField(default=False),
        ),
    ]
