# Generated by Django 4.2.30 on 2026-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0028_project_is_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='extracted_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='priority_ordered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='phase',
            field=models.CharField(choices=[('chat_initializing', 'Chat Initializing'), ('exploring', 'Exploring'), ('analyzing', 'Analyzing'), ('converged', 'Converged'), ('completed', 'Completed')], default='exploring', max_length=20),
        ),
    ]
