# Generated by Django 4.2.30 on 2026-09-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0031_remove_qcard_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionevent',
            name='event_type',
            field=models.CharField(choices=[('session_start', 'Session Start'), ('pool_creation', 'Pool Creation'), ('swipe', 'Swipe'), ('confidence_update', 'Confidence Update'), ('session_end', 'Session End'), ('session_extend', 'Session Extend'), ('bookmark', 'Bookmark'), ('detail_view', 'Detail View'), ('external_url_click', 'External URL Click'), ('failure', 'Failure'), ('probe_turn', 'Probe Turn'), ('cohort_assignment', 'Cohort Assignment'), ('parse_query_timing', 'Parse Query Timing'), ('hyde_call_timing', 'HyDE Call Timing'), ('hybrid_pool_timing', 'Hybrid Pool Timing'), ('stage2_timing', 'Stage 2 Timing'), ('image_load', 'Image Load'), ('persona_image_timing', 'Persona Image Timing')], db_index=True, max_length=32),
        ),
    ]
