/*
 * project/state.js — ArchiTinder Make Web project state.
 *
 * Generated by the `reporter` agent at session end. Hand-edited only inside
 * `systemFlow` / `recommendationFlow` / `agentFlow` Mermaid bodies and the
 * `milestones` archive (semi-static), all other sections are rebuilt from
 * `.claude/Task.md`, `gh pr list`, and `.claude/agents/*.md` frontmatter.
 *
 * Loaded via <script> by `project/dashboard.html`, which opens by double-click
 * via file:// — no fetch, no server, no build step.
 *
 * Three-bucket model:
 *   - `done`      = resolved work (merged, shipped, archived)
 *   - `now`       = current initiative slice (one or more PRs in flight)
 *   - `next`      = backlog / planned / deferred work
 *
 * Time convention: all human-facing timestamps are `YYYY-MM-DD HH:mm KST`.
 * PRs additionally carry the raw `mergedAt` (ISO 8601 UTC from `gh pr list`)
 * so the value can be re-parsed by any consumer.
 */
// Reporter: Mermaid sources may be stale — commit 18949a8 touched .claude/agents/reporter.md. Next session should refresh the affected diagram by hand.
window.PROJECT_STATE = {
  meta: {
    name: 'ArchiTinder — Make Web',
    updatedAt: '2026-05-24 23:59 KST',
    head: '18949a8',
    branch: 'develop',
  },

  done: [
    {
      id: 'TASK-NEXT-RESTRUCTURE',
      title: '#18 TASK-NEXT-RESTRUCTURE — absorb docs/specs into Task.md Next, fix orchestrate stale refs',
      completedAt: '2026-05-24',
      prs: [101],
      note: 'docs/specs/*.md (4 files) absorbed into Task.md ## Next flat backlog, folder deleted. orchestrate/SKILL.md stale refs fixed (Goal.md → CLAUDE.md constitution, Report.md → code+state.js, token-saving.md → WORKFLOW.md). 10 operational deferrals surfaced as ## Next entries. reporter.md sub-step 2a added (Deferred→Next surfacing). back-maker/front-maker/code-review agent refs updated.',
    },
    {
      id: 'PRODUCT-IDENTITY',
      title: '#17 PRODUCT-IDENTITY — add Product Identity section to CLAUDE.md (Core Promise anchor)',
      completedAt: '2026-05-24',
      prs: [100],
      note: 'New ## Product Identity section added to CLAUDE.md between What This Repo Does and Branch Model. ### Core Promise sub-section: 10-15 swipes → Aha! moment, Korean user-quote anchor, two-pillars one-liner (algorithm + corpus), pointer to docs/algorithm.md. Surfaces positive product identity previously implicit. +8 lines.',
    },
    {
      id: 'DEPLOY-2026-05-24-v2',
      title: '#16 DEPLOY-2026-05-24-v2 — develop → main deploy, 1 PR (#97)',
      completedAt: '2026-05-24',
      prs: [98],
      note: 'Release PR #98 squash-merged CI hang fix to main (fd063e0). Railway deployment a98725bf Online. Bug #5 carve-out applied (develop force-reset to fd063e0). Prod functional pre-deploy (PR #94 cap working); this deploy = CI baseline alignment + main/develop sync.',
    },
    {
      id: 'CI-HANG-FIX',
      title: '#15 CI-HANG-FIX — _retry_gemini_call executor → daemon Thread + Queue',
      completedAt: '2026-05-24',
      prs: [97],
      note: 'ThreadPoolExecutor + future.result(timeout) → threading.Thread(daemon=True) + queue.Queue.get(timeout). _Thread captured at module-load to bypass test_imp8 _DiscThread global mock leak. Same 15s/45s deadline + FATAL + retry semantics. PR #94 ThreadPoolExecutor hung pytest CI 15min, cascading 5 CI failures. Full suite: 683 passed / 11 skipped / 0 failed.',
    },
    {
      id: 'GEMINI-TIMEOUT-CAP',
      title: '#13 GEMINI-TIMEOUT-CAP — hard 15s timeout cap on Gemini retry wrapper',
      completedAt: '2026-05-24',
      prs: [94],
      note: '_retry_gemini_call caps every Gemini SDK call at 15s (45s Imagen3) via ThreadPoolExecutor + future.result(timeout). 228s /parse-query/ hang → ≤31s. 4 new tests + 5 regression. Deferred: _caches.py:92 IMP-5 create call bypasses wrapper (context_caching_enabled default False, zero prod impact).',
    },
    {
      id: 'BUILDINGS-DB-SWAP',
      title: '#12 BUILDINGS-DB-SWAP — buildings DB neondb → archi_data + make_web role',
      completedAt: '2026-05-24',
      prs: [93],
      note: 'Make DB renamed buildings DB neondb → archi_data; new SELECT-only role make_web (was neondb_owner); canonical_v2_architects table added (14,216 firms). Make Web swapped .env + Railway prod env vars; refreshed .env.example + CLAUDE.md is_publishable stat (39/39,776 → 2,614/39,478 ~6.6%) + docs/database-schema.md. Prod redeploy 04e7633e Online verified.',
    },
    {
      id: 'V1-LEGACY-CLEANUP',
      title: '#11 V1-LEGACY-CLEANUP — drop architecture_vectors refs + orphan tables',
      completedAt: '2026-05-24',
      prs: [92],
      note: 'Neondb local-dev branch drop + 23 orphan user/app tables + legacy architecture_vectors dropped. 3 backend v1 files deleted (algorithm_tester.py, profile_image_latency.py, test_chat_phase_style_labels). 5 stale doc refs refreshed. Plan merry-toasting-dove.md archived.',
    },
    {
      id: 'DEPLOY-2026-05-24',
      title: 'develop → main deploy — 21 PRs (#68–#89)',
      completedAt: '2026-05-24',
      prs: [90],
      note: 'Release PR #90 squash-merged 21 PRs to main (179d6f6). Railway prod confirmed Online. origin/develop force-reset to match main (Bug #5 carve-out).',
    },
  ],

  now: [],

  next: [
    {
      id: 'AUTH1',
      title: 'Kakao / Naver OAuth',
      note: 'Google OAuth only today. Korean users need domestic login. Backend + frontend buttons for both.',
    },
    {
      id: 'AUDIT-T4',
      title: 'Audit Tier 4 — structural refactor (deferred)',
      note: 'File decomp: engine.py (2079 LOC), App.jsx (795 LOC), BoardDetailPage (1032 LOC), UserProfilePage (990 LOC), PostSwipeLandingPage (696 LOC), SwipePage (666 LOC), FirmProfilePage (611 LOC).',
    },
    {
      id: 'PHASE16',
      title: 'Phase 16 — Recommendation expansion (Profile-tab 사무소/유저 추천)',
      note: 'REC1 shipped as Push S3. REC2 (firm) + REC3 (user) target GET /api/v1/recommendations/profile/ returning {offices, users} for a Profile-tab button. Open: firm vector composition, user taste vector, cold-start strategy, match score visibility, diversity/follow-exclusion, tie-breakers, trigger surface UX. Acceptance: p95 ≤800ms Singapore, cold-start graceful, is_publishable=true gating preserved.',
    },
    {
      id: 'PHASE17',
      title: 'Phase 17 — LLM reverse-questioning (pre-swipe persona classification P1-P4)',
      note: 'Reverse-question in first 0-2 turns of Taste-tab LLM chat (Q6 Option A confirmed 2026-05-14). Populates UserProfile.persona_summary. Open: reverse-Q examples, per-persona UI branching, persona drift, representation shape, persistence, confidence+override. Acceptance: TTFC Taste-tab chat ≤4000ms; persona override path tested.',
    },
    {
      id: 'PHASE18',
      title: 'Phase 18 — External connections (firm article crawl)',
      note: 'Lowest pending priority. Surfaces external articles about a firm on FirmProfilePage (Space / ArchDaily / news keyword match). Phase 15 already shipped External DM wiring. Open: article source priority, crawl freshness, storage, article fallback. Acceptance: ≤10 most recent articles per firm, open in new tab, no FirmProfilePage TTFC regression.',
    },
    {
      id: 'XSESS',
      title: 'Cross-session signal transfer (deferred)',
      note: 'liked_ids / pref_vector carry-over between sessions. Current spec: implicit independence (each session starts fresh). Six options A–F. Defer until traffic justifies experiment cost.',
    },
    {
      id: 'EMPTY-STATE',
      title: 'Empty-state UX (Project = 0)',
      note: 'First-time user with 0 projects sees Home → project picker. Need explicit empty-state path: guided flow / empty-state + create button / demo query. Low priority — current users are existing accounts.',
    },
    {
      id: 'MULTILANG',
      title: 'Multi-language behavior (partial)',
      note: 'Chat phase has bilingual rendering rule. Mobile UI / detail page / persona report multi-language posture unresolved. Korea-first per Constitution Decision Principle 7; English supported, not co-equal.',
    },
    {
      id: 'MOBILE-DESKTOP',
      title: 'Mobile vs desktop UX divergence',
      note: 'Current viewport-lock layout is mobile-first. Detail pages on desktop work but unoptimised. Low priority — desktop is secondary.',
    },
    {
      id: 'PRIVACY-PIPA',
      title: 'Privacy / sharing posture (PIPA + GDPR)',
      note: 'Phase 13+ Profile/Board public/private visibility shipped. PIPA + GDPR posture for signup data collection / consent flow / retention policy still open. Required before public launch.',
    },
    {
      id: 'CONVO-PERSIST',
      title: 'Conversation history persistence',
      note: 'Probe-turn chat history during a session is currently transient. Persist for session resume? Low priority.',
    },
    {
      id: 'IMP5-BYPASS',
      title: 'IMP-5 cache create timeout wrapper bypass',
      note: 'backend/apps/recommendation/services/_caches.py:92 IMP-5 Gemini context-cache create call bypasses the _retry_gemini_call timeout wrapper. Gated by context_caching_enabled flag (default OFF) — zero prod impact until toggled on. Wrap on toggle-on.',
    },
    {
      id: 'CODEX-STAGE3-RERUN',
      title: 'Codex Stage 3 re-audit on prod (post-PR #97)',
      note: 'CI hang fix (PR #97) deployed via PR #98. Re-run codex Stage 3 (AI Search Flow 5) against prod to verify the 228s /parse-query/ hang no longer fires under load. Cumulative validation of PR #94 timeout cap + PR #97 daemon-thread swap.',
    },
    {
      id: 'PERF-PROJECTS',
      title: '/projects/ p50 600ms (budget 300ms)',
      note: 'Codex Round 2: /projects/ p50 latency 600ms vs spec budget 300ms. Probable N+1 or warm cache miss. Investigate query plan.',
    },
    {
      id: 'PERF-DISCOVERY',
      title: 'Discovery cache-hit 450ms (budget <200ms)',
      note: 'Codex Round 2: Discovery endpoint cache-hit path measures 450ms; spec budget <200ms. Cache may be doing extra work or response serialization is the floor. Trace.',
    },
    {
      id: 'PERF-SESSION-CREATE',
      title: 'Session create 5.2s baseline',
      note: 'POST /analysis/sessions/ measured 5.2s baseline. Pre-existing; flag for investigation.',
    },
    {
      id: 'MATMUL-WARN',
      title: 'matmul runtime warning (sklearn BLAS dtype)',
      note: 'sklearn emits matmul dtype warning during clustering. Cosmetic noise but indicates float32/float64 mismatch — quick fix is dtype-align embedding ndarrays before kmeans.',
    },
    {
      id: 'ARCHITECTS-WIRING',
      title: 'canonical_v2_architects feature wiring',
      note: 'Make DB shipped canonical_v2_architects (14,216 firms, 4,357 recommendable) in 2026-05-24 DB swap. Make Web profiles_office 4-tier resolution + REC2 (Phase 16) should consume this. Not yet wired.',
    },
    {
      id: 'USER-DATA-ROLE-SEP',
      title: 'user_data DB role separation (security)',
      note: 'user_data DB currently uses default neondb_owner role with full privileges. Split to a restricted Make-Web-only role mirroring the SELECT-only make_web role on archi_data. Security backlog.',
    },
    {
      id: 'SNAPSHOT-BRANCH-DROP',
      title: '1-week post-deploy snapshot branch drop',
      note: 'After production deploys, Neon snapshot branches retained for 1 week as rollback safety. Drop the lingering ones after retention window (verify Neon dashboard).',
    },
    {
      id: 'CELERY-CORPUS-RANK',
      title: 'Celery compute_corpus_rank background task',
      note: 'recommendation_swipeevent row inserts currently compute corpus rank synchronously (or skip when on bookmark POST per PR #79). Async via Celery for proper telemetry without blocking.',
    },
    {
      id: 'DESIGN-REWORK',
      title: 'Design-system redesign per-component rework (paused)',
      note: 'Foundation shipped: PR #54 (tokens.css 4 themes + ThemeContext + AppearanceSettings) + PR #59 (theme/font server persistence). Remaining: per-component visual rework (~7,700 LOC, inline styles → CSS Modules + :hover, light-theme visuals) across the frontend, leaf→hub order. Paused — no active PR. Resume via /plan per slice.',
    },
  ],

  prs: [
    {
      number: 101,
      title: 'docs: absorb docs/specs into Task.md Next, fix orchestrate stale refs',
      mergedAt: '2026-05-24T14:56:47Z',
      mergedAtKST: '2026-05-24 23:56 KST',
    },
    {
      number: 100,
      title: 'docs: add Product Identity section to CLAUDE.md (Core Promise anchor)',
      mergedAt: '2026-05-24T14:34:59Z',
      mergedAtKST: '2026-05-24 23:34 KST',
    },
    {
      number: 99,
      title: 'chore: session-end reporter housekeeping — CI hang fix + deploy #98',
      mergedAt: '2026-05-24T11:03:09Z',
      mergedAtKST: '2026-05-24 20:03 KST',
    },
    {
      number: 97,
      title: 'fix(gemini): swap executor for daemon Thread + Queue (CI hang)',
      mergedAt: '2026-05-24T08:01:27Z',
      mergedAtKST: '2026-05-24 17:01 KST',
    },
    {
      number: 95,
      title: 'chore: session-end reporter housekeeping — PRs #92/#93/#94 + plan archive',
      mergedAt: '2026-05-24T04:30:44Z',
      mergedAtKST: '2026-05-24 13:30 KST',
    },
    {
      number: 94,
      title: 'fix(gemini): hard 15s timeout cap on retry wrapper (228s hang → ≤31s)',
      mergedAt: '2026-05-24T04:26:12Z',
      mergedAtKST: '2026-05-24 13:26 KST',
    },
    {
      number: 93,
      title: 'chore: buildings DB swap to archi_data + make_web role (config + docs)',
      mergedAt: '2026-05-24T03:19:05Z',
      mergedAtKST: '2026-05-24 12:19 KST',
    },
    {
      number: 92,
      title: 'chore: drop v1 architecture_vectors refs — 2 files + 4 doc fixes',
      mergedAt: '2026-05-24T01:42:39Z',
      mergedAtKST: '2026-05-24 10:42 KST',
    },
  ],

  agents: [
    {
      name: 'back-maker',
      role: 'Django/DRF backend code — only touches files inside backend/. Runs flake8 after changes.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'front-maker',
      role: 'React/Vite frontend code — only touches files inside frontend/. Runs ESLint after changes.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'code-review',
      role: 'Static code review — integration correctness, API contracts, logic bugs, error handling. Inner loop, per change, pre-commit.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'security-manager',
      role: 'Security scan — SQL injection, auth bypass, secret leakage, XSS, token storage. Inner loop, per change, pre-commit.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'app-test',
      role: 'Pre-push gate — live-browser 3-persona swipe journey + drift check. FULL or FEATURE-SCOPED mode.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'git-manager',
      role: 'Single commit — stages changed files (excluding secrets), writes caveman-terse conventional-commit message. Never pushes.',
      model: 'haiku',
      effort: 'default',
    },
    {
      name: 'git-publisher',
      role: 'Push + PR open/poll + squash merge + branch cleanup + develop→main deploy PRs. Never commits source code.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'reporter',
      role: 'Session-end — updates Task.md, regenerates this dashboard state, conditionally syncs docs/algorithm.md.',
      model: 'sonnet',
      effort: 'default',
    },
  ],

  systemFlow: {
    title: 'System Flow — Browser → Vercel → Django → DBs / external services',
    mermaid: `flowchart LR
  Browser["Browser"]
  Vercel["Vercel React<br/>frontend/src"]
  ApiClients["Frontend API clients<br/>frontend/src/api/{auth,sessions,projects,<br/>discovery,profiles,social,images}.js"]
  Django["Django backend<br/>backend/config/urls.py"]
  Apps["apps.accounts · apps.recommendation<br/>apps.profiles · apps.social"]
  Views["views/{sessions,swipe,search,projects,<br/>reports,discovery,telemetry}.py"]
  Engine["engine.py<br/>services/parse_query.py"]
  DefaultDB[("default DB · Neon<br/>User · Project · AnalysisSession · SwipeEvent")]
  BuildingsDB[("buildings DB · Neon<br/>canonical_v2_buildings (read-only raw SQL)")]
  Gemini["Gemini API"]
  R2["Cloudflare R2 image CDN"]
  OAuth["Google · Kakao · Naver OAuth"]

  Browser --> Vercel --> ApiClients --> Django --> Apps --> Views
  Views --> Engine
  Views --> DefaultDB
  Engine --> BuildingsDB
  Engine --> Gemini
  Views --> OAuth
  Browser -. images .-> R2`,
  },

  recommendationFlow: {
    title: 'Recommendation / Swipe Flow — LLM parse → swipe loop → result',
    mermaid: `flowchart TD
  Search["LLMSearchPage.jsx"]
  ParseAPI["POST /api/v1/parse-query/<br/>ParseQueryView"]
  ParseSvc["services/parse_query.py<br/>Gemini chat · structured_filters<br/>visual_description"]
  SessionCreate["POST /api/v1/analysis/sessions/<br/>SessionCreateView"]
  SwipeUI["SwipePage.jsx"]
  SwipeAPI["POST /api/v1/analysis/sessions/&lt;id&gt;/swipes/<br/>SwipeView"]
  Engine["engine.py<br/>compute_mmr_next · farthest_point_from_pool<br/>refresh_pool_if_low · compute_taste_centroids"]
  RawSQL[("canonical_v2_buildings<br/>raw SQL · is_publishable=true")]
  ResultUI["ResultsPage.jsx"]
  ResultAPI["GET /api/v1/analysis/sessions/&lt;id&gt;/result/<br/>SessionResultView"]
  Reports["reports.py<br/>generate_report · generate_report_image"]

  Search --> ParseAPI --> ParseSvc --> SessionCreate
  SessionCreate --> SwipeUI
  SwipeUI --> SwipeAPI --> Engine --> RawSQL
  Engine --> SwipeUI
  SwipeUI -- converged --> ResultUI --> ResultAPI --> Engine
  ResultUI --> Reports`,
  },

  agentFlow: {
    title: 'Agent Flow — Main Session → orchestrate skill → 8 agents',
    mermaid: `flowchart LR
  Session["Main Session<br/>opus 4.7 · architecture · plan · dispatch"]
  Orchestrate["orchestrate skill<br/>feature implementation playbook"]
  BackMaker["back-maker · sonnet"]
  FrontMaker["front-maker · sonnet"]
  Review["code-review · sonnet"]
  Security["security-manager · sonnet"]
  GitMgr["git-manager · haiku"]
  AppTest["app-test · sonnet"]
  GitPub["git-publisher · sonnet"]
  Reporter["reporter · sonnet"]

  Session --> Orchestrate
  Orchestrate --> BackMaker
  Orchestrate --> FrontMaker
  BackMaker --> Review
  FrontMaker --> Review
  Review --> Security
  Security --> GitMgr
  GitMgr --> AppTest
  AppTest --> GitPub
  GitPub --> Reporter
  Reporter -. session-end .-> Session`,
  },

  milestones: [
    { phase: '1–12', focus: 'Single-user reference exploration base (auth, 4-phase recommendation, Gemini search, persona report, project CRUD, E2E infra)', status: 'shipped' },
    { phase: '13', focus: 'Profile system — firm + user profiles, public/private boards', status: 'shipped' },
    { phase: '14', focus: 'Board system — board detail view, follow, "Love this!" reaction', status: 'shipped' },
    { phase: '15', focus: 'Social foundation — external DM links, MATCHED! results screen', status: 'shipped' },
    { phase: '16', focus: 'Recommendation expansion — Profile-tab office + user recs', status: 'pending' },
    { phase: '17', focus: 'LLM reverse-questioning — pre-swipe persona classification', status: 'pending' },
    { phase: '18', focus: 'External connections — firm article crawl (Space, ArchDaily, news)', status: 'pending' },
    { phase: '19–26', focus: 'Tab 3-structure replan + P1–P6 latency/UX overhaul', status: 'shipped' },
    { phase: 'design', focus: 'Design-system redesign — light-mode tokens, 4-theme switcher, frontend rework', status: 'in progress' },
  ],
};
