/*
 * project/state.js — ArchiTinder Make Web project state.
 *
 * AUTO-GENERATED by tools/gen-state.js (DASHBOARD-AUTOGEN-1, 2026-06-01+).
 * Do NOT hand-edit the auto sections — re-run `node tools/gen-state.js` instead.
 * Hand-curated keys (systemFlow / recommendationFlow / agentFlow / milestones, and
 * each done/next note + agent role) are carried verbatim from the prior file; edit
 * those in the prior state.js (or Task.md for new note seeds) and re-run.
 *
 * Per-key source:
 *   meta/done/now/next  <- Task.md (+ git for meta)            [auto]
 *   agents              <- .claude/agents/<name>.md frontmatter [auto]
 *   prs                 <- gh pr list (prior on offline)        [auto]
 *   fileTree            <- git ls-files U project/file-roles.json [auto]
 *   systemFlow/recommendationFlow/agentFlow/milestones          [hand-curated, carried]
 *
 * Loaded via <script> by project/dashboard.html (file:// double-click — no fetch,
 * no server at LOAD time; generation is the build step).
 *
 * Time convention: human-facing timestamps are `YYYY-MM-DD HH:mm KST`; PRs also
 * carry raw ISO 8601 UTC (mergedAt).
 */
window.PROJECT_STATE = {
  meta: {
    name: 'ArchiTinder — Make Web',
    updatedAt: '2026-06-04 19:39 KST',
    head: 'df8dcd8',
    branch: 'feature/claude-back-recommend-4',
  },
  done: [
    {
      id: 'BACK-RECOMMEND-4',
      title: 'Discovery 좋아요가 추천에 반영 (taste vector + exclude + evict)',
      completedAt: '2026-06-04',
      note: 'Discovery 우-스와이프 like(`UserProfile.liked_building_ids`)가 추천 엔진에 안 먹히던 것 해결 — Discovery-only 유저가 영구 cold/random feed였던 core-promise 위반 수정. 3곳 주입, 전부 기존 infra 재사용.',
    },
    {
      id: 'ARCHITECT-UNIFY-C',
      title: 'OfficeFollow 중복 제거 (follow 모델 통합)',
      completedAt: '2026-06-04',
      note: '미배선 중복 `OfficeFollow`(firm-follow, ArchitectFollow와 중복) 제거 → office-interest follow 모델이 ArchitectFollow 1개로 통합(원 audit 중복 finding 종결). Office 서브시스템 나머지는 계획 기능 substrate라 park.',
    },
    {
      id: 'BACK-PROFILE-1',
      title: 'external_links 검증 강화 (handle/email/website + mailto 주입 차단)',
      completedAt: '2026-06-04',
      note: '`validate_external_links`(accounts/serializers.py)에 키별 포맷 검증 추가 — 프론트가 검증 없이 `instagram.com/${handle}`·`mailto:${email}` 평문 조립하던 주입 nuisance를 서버에서 차단.',
    },
    {
      id: 'BACK-OFFICE-1',
      title: '(ARCHITECT-UNIFY Phase 0) — SavedOffice orphan 제거',
      completedAt: '2026-06-04',
      note: '예원 #180의 미배선 SavedOffice(model+2뷰+2url) 삭제 + DROP 마이그 0005. ARCHITECT-UNIFY(Office↔Architect 통합) 스펙의 첫 안전 조각 — "스튜디오 저장"은 ArchitectFollow saved-studios(#179)가 이미 충족, SavedOffice는 프론트 콜러 0이라 무위험.',
    },
    {
      id: 'UX-WRITE-FAIL',
      title: '쓰기 실패 무음 유실 표면화 (FRONT-UX-8 + FRONT-UX-7)',
      completedAt: '2026-06-04',
      note: '두 쓰기 POST 실패를 빈 `.catch(()=>{})`로 삼켜 취향신호(질문답변·좋아요)가 조용히 유실되던 것을 공유 토스트로 표면화. 기존 `globalToast` 재사용(새 이벤트 시스템 없음).',
    },
    {
      id: 'DASHBOARD-LOCALVIEW-REMOVE',
      title: 'state.local.js 그림자 메커니즘 제거',
      completedAt: '2026-06-04',
      note: '`make dashboard`가 만드는 gitignored `project/state.local.js`가 신선도 가드 없이 committed `state.js`를 가리는 footgun 제거. 6/1 stale local이 6/4 audit 변경(BACK-OFFICE-1·BACK-PROFILE-1 등)을 영구히 가려 유저가 대시보드에서 못 봄. 대시보드 단일 소스 = committed `state.js`.',
    },
    {
      id: 'FRONT-PROFILE-HARVEST-1',
      title: '프로필 컴포넌트 하베스트 + 인스타식 재설계',
      completedAt: '2026-06-04',
      prs: [179],
      note: 'archibe-profile에서 핵심 컴포넌트 채택 + 4테마 재토큰화 + 프로필 인스타식 재설계. Profile-area 컴포넌트 하베스트 + CSS-Module/hook 패턴 토대 — 명명된 ~646 인라인 부채(SwipePage/BoardDetailPage 등) 상환 아님(그 파일 안 건드림); FRONT-DESIGN-1 핵심 인라인 마이그레이션은 ## Next 잔존.',
    },
    {
      id: 'DASHBOARD-AUTOGEN-1',
      title: '대시보드 Files 탭 + state.js 자동생성',
      completedAt: '2026-06-01',
      note: '프로젝트 대시보드 2건: (1) 파일 구조 Files 탭 (collapsible 트리 + 파일별 role), (2) state.js를 reporter 수작업 재작성 대신 `tools/gen-state.js`로 자동생성.',
    },
  ],
  now: [
    {
      id: 'FRONT-AUTH-2',
      title: '로그인 스와이프 온보딩',
      note: 'Redesign `/login` as conversational swipe onboarding while preserving the existing guest auth API contract. 1차 merged to develop 2026-06-01 (Codex; code-review + security PASS, no blockers; further passes + PIPA copy pending).',
    },
  ],
  next: {
    xhigh: [
      {
        id: 'FRONT-UX-6',
        title: 'SwipeCard gallery flip 부모 state 동기화 누락  [BUNDLE UX-GALLERY anchor, promoted from MEDIUM 2026-06-04]',
        note: 'PR #158 (`0071c3f`, 2026-05-29) restored in-card gallery flip but made `openGallery()` purely local — it no longer notifies the parent page via `onGalleryOpen` callback. SwipePage\'s `galleryOpen` state never flips to `true`. Two visible regressions on the swipe surface:',
      },
      {
        id: 'FRONT-UX-9',
        title: '모바일 갤러리 세로 스크롤 깨짐 (검증 필요)  [BUNDLE UX-GALLERY, needs browser repro]',
        note: '2026-05-31 리뷰 F4 (high-confidence, 브라우저 미확인). SwipeCard.jsx:183 root touchAction:none + react-tinder-card index.js:174-176 touchstart preventDefault (className에 pressable 없으면) → 카드 내 갤러리 세로 스크롤 native gesture 취소 추정. PR #158 flip 복원 회귀 가능. VERIFY FIRST: 390x844 뷰포트에서 갤러리 세로 드래그. 깨지면 fix=갤러리 스크롤 div에 touchAction:pan-y + pressable className. 재현 안 되면 downgrade/close.',
      },
      {
        id: 'FRONT-UX-10',
        title: 'Discovery 갤러리 위 long-press 오작동  [BUNDLE UX-GALLERY, promoted from MEDIUM 2026-06-04]',
        note: 'On the Discovery page (desktop only), pressing-and-holding the mouse (>400ms) over an open card gallery opens the Save-to-Board modal over it, because the gallery\'s pointer-event `stopPropagation` does not stop the separate `mousedown` that DiscoveryPage\'s long-press listener…',
      },
    ],
    high: [
      {
        id: 'ARCHITECT-UNIFY-1',
        title: 'firm-side Office→Architect 전면 통합 (deferred, firm-UX 착수 시)',
        note: 'office-interest 모델 중복 해소됨: Phase 0(SavedOffice #188) + C(OfficeFollow, ARCHITECT-UNIFY-C)로 두 미배선 중복 삭제 → follow 모델 1개(ArchitectFollow). 남은 통합 = Office 서브시스템(table/claim/sync_offices/FirmProfilePage) arch_id 흡수 = firm-side 전면 재설계, deferred(firm-UX 착수 시). Office는 계획 기능 substrate(BACK-RECOMMEND-3/EXTERNAL-1/firm-claim)라 park.',
      },
      {
        id: 'BACK-RECOMMEND-1',
        title: 'Project 두번째 세션이 이전 taste를 모름',
        note: 'Code audit 2026-05-27: SessionCreateView resolves project_id only to skip dedupe; session_insert still creates phase=exploring with empty like_vectors/convergence/preference state. Project.liked_ids/disliked_ids/saved_ids persist but are not read. Primary edit: views/sessions.py warm-start policy + engine.get_pool_embeddings(project liked_ids) scoped to active project; tests in test_session_create_correctness.py for no cross-project leakage and progress semantics.',
      },
      {
        id: 'FULL-LANGUAGE-1',
        title: '한/영 언어 설정 토글 없음',
        note: 'Code audit 2026-05-27: UserProfile preferences are theme/font only; UserSerializer and UserProfileSelfUpdateSerializer need language parity. ThemeContext + AppearanceSettings are the local persistence/UI pattern. ParseQueryView currently calls services.parse_query(conversation_history) with no user preference, so language must be passed from request.user.profile.language and prompt inference overridden.',
      },
      {
        id: 'BACK-LLM-2',
        title: '채팅 기록이 다른 기기에서 사라짐',
        note: 'Code audit 2026-05-27: LLMSearchPage stores messages/conversationHistory/latest* under archithon_chat_${userId}_${mode}_${projectId||new}; backend Project only has raw_query and AnalysisSession has no chat field. ParseQueryView validates conversation_history but does not persist it. Likely edit: Project conversation_history or ConversationTurn + dedicated idempotent append endpoint + frontend write-through cache.',
      },
      {
        id: 'FRONT-DESIGN-1',
        title: '디자인 시스템 컴포넌트 리워크 (paused)',
        note: 'Code audit 2026-05-27: 581 inline style call sites. Largest FE files: BoardDetailPage 1049, UserProfilePage 992, App 838, BuildingDetailPage 711, SwipePage 683, FirmProfilePage 540. tokens.css exists; index.css is mostly utilities. Slice leaf components first (ArticleCard/ProjectCard/BoardCard), then SwipeCard/BuildingDetailPage; each slice lint+build+screenshot.',
      },
    ],
    medium: [
      {
        id: 'FRONT-PROFILE-1',
        title: '프로필 재설계 브라우저 픽셀 패스 (Codex)',
        note: 'FRONT-PROFILE-HARVEST-1(#179) 머지 후 Codex 브라우저 수정 (별도 PR). FollowListModal 모바일 bottom-sheet(≤768px, DESIGN.md §8.10) + backdrop opacity 0.6→0.4 + inline onMouseEnter→CSS hover + 4테마 픽셀 검증(github-light 먼저). 원 하베스트 minor (2026-06-04 audit 재확인): EditProfileModal(`components/EditPr…',
      },
      {
        id: 'BACK-AUTH-3',
        title: 'LikedBuildingsView guest 사용자 가드 정책 확인',
        note: 'PR #157 (`77ffd6e`, 2026-05-29) added `LikedBuildingsView` with `permission_classes = [IsAuthenticated]` only. No `is_guest=False` check. Guest users (post-FULL-LOGIN-REDESIGN-1: `UserProfile.is_guest=True`, no email, no SocialAccount) can freely write to `UserProfile.liked_bu…',
      },
      {
        id: 'BACK-PERFORMANCE-5',
        title: 'Swipe latency 0.7-1.5s 흔들림',
        note: 'Code audit 2026-05-27: SwipeView still does update/phase/refresh_pool/get_pool_embeddings/MMR-or-farthest selection in request transaction. Async prefetch only helps after next_bid is selected. Use existing [SWIPE TIMING] lock/embed/select/prefetch/total + embedding cache stats to bucket variance before code changes.',
      },
      {
        id: 'BACK-AUTH-2',
        title: 'Cache JWT 통합 테스트 hardening',
        note: 'Code audit 2026-05-27: CachedJWTAuthentication cache-hit returns cached_user directly; signals invalidate User save/delete but not bulk update. test_jwt_cache is unit-level with patched cache and mocked tokens. Add DRF pipeline tests via /auth/me, signal invalidation test, stale inactive-user cache negative test, and cross-instance shared-cache check.',
      },
      {
        id: 'INFRA-DB-2',
        title: 'test DB role permissions for CREATE DATABASE',
        note: 'Code audit 2026-05-27: settings.py imports PG default/buildings from env; .env.example correctly says runtime role make_web_app has NOCREATEDB. Root conftest tries SQLite/mirrored buildings, but app-local conftests differ and some invocations still hit pytest-django DB creation. Decide make_web_test CREATEDB vs --reuse-db preprovisioned test_user_data vs temporary owner swap; document in CONTRIBUTING + backend/.env.example.',
      },
      {
        id: 'FRONT-LAYOUT-1',
        title: 'Desktop wide-screen 레이아웃 어색함',
        note: 'Code audit 2026-05-27: body is 100vh/overflow hidden and each page owns scroll. BuildingDetail stays maxWidth 820 with only masonry media query; BoardDetail/UserProfile maxWidth 1100 but hero/profile remain mobile-centered. Start with BuildingDetail desktop split, then Board/User grids.',
      },
      {
        id: 'FULL-LEGAL-1',
        title: 'PIPA/GDPR consent 없음 (public launch 차단)',
        note: 'Partial mitigation shipped via FULL-LOGIN-REDESIGN-1: UserProfile.consent_accepted_at + consent_policy_version fields + terminal-style "동의합니다" capture on guest wizard. Still pending: legally-reviewed copy, Privacy/Terms routes, retention/export/delete flow. PIPA-compliant copy + UI/UX legal review required before public launch.',
      },
      {
        id: 'BACK-PERFORMANCE-6',
        title: 'Neon connection pool 고갈 위험 (async prefetch thread)',
        note: 'PR 4 PERF-PREFETCH-CHAIN flipped `async_prefetch_enabled: True` — every prod swipe now spawns a daemon thread holding its own DB connection until `_connections.close_all()` runs in finally. Under high concurrent swipe load: connections ≈ (concurrent_requests × 2) — one main wo…',
      },
      {
        id: 'INFRA-DB-3',
        title: 'Unverified guest row 누적 정리 (conditional)',
        note: 'Guest 계정(FULL-LOGIN-REDESIGN-1 #154/#155)은 정리 로직 없음 (user Q5 결정). `/auth/guest/` throttle 3/min/IP이나 IP 로테이션 botnet은 row 증가 가능 → 조건부 모니터링 항목.',
      },
    ],
    low: [
      {
        id: 'FRONT-AUTH-1',
        title: 'LoginPage에 Kakao/Naver 버튼 없음',
        note: 'Code audit 2026-05-27: api/auth.js already supports generic socialLogin(provider). Backend has Kakao/Naver endpoints; LoginPage rewrite (FULL-LOGIN-REDESIGN-1 PR #155) now uses terminal-style wizard but Kakao/Naver still missing. After FULL-LOGIN-REDESIGN-1 ships, Kakao/Naver should be secondary upgrade options on returning-user CTA + Settings → linked-providers section.',
      },
      {
        id: 'BACK-RECOMMEND-3',
        title: 'Profile-tab 사무소/유저 추천 endpoint 없음',
        note: 'Code audit 2026-05-27: no /recommendations/profile/ route exists. Office + OfficeProjectLink models and OfficeDetail project hydration exist; social Follow/ArchitectFollow exists for exclusions (OfficeFollow removed in ARCHITECT-UNIFY-C). engine.compute_user_taste_vector helps requester taste only; firm/user recommendations need cached/precomputed vectors, not per-request loops. Cold-start branch required.',
      },
      {
        id: 'BACK-EXTERNAL-1',
        title: 'FirmProfilePage에 외부 기사 surface 없음',
        note: 'Code audit 2026-05-27: FirmProfilePage already renders office.articles when present and ArticleCard expects {title,url,source,date}; backend serializer explicitly excludes articles and Office model has no article table. Add async/cached endpoint or OfficeArticle model; do not block OfficeDetail TTFC.',
      },
      {
        id: 'INFRA-QUEUE-1',
        title: 'corpus_rank telemetry 꺼져있음',
        note: 'Code audit 2026-05-27: engine.compute_corpus_rank still exists as corpus-wide pgvector ROW_NUMBER query, but ProjectBookmarkView sets bookmark telemetry rank_corpus=None and tests assert it is not called. Do not restore sync path; only background queue with tests moving from placeholder-null to enqueued-job semantics. Low until more background jobs justify worker infra.',
      },
    ],
  },
  prs: [
    {
      number: 190,
      title: 'refactor(social): delete OfficeFollow duplicate (ARCHITECT-UNIFY-C)',
      mergedAt: '2026-06-04T08:39:41Z',
      mergedAtKST: '2026-06-04 17:39 KST',
      sha: 'df8dcd8',
    },
    {
      number: 189,
      title: 'security(accounts): harden external_links validation (BACK-PROFILE-1)',
      mergedAt: '2026-06-04T07:12:58Z',
      mergedAtKST: '2026-06-04 16:12 KST',
      sha: 'e60918d',
    },
    {
      number: 188,
      title: 'refactor(profiles): delete SavedOffice orphan (ARCHITECT-UNIFY Phase 0)',
      mergedAt: '2026-06-04T07:10:18Z',
      mergedAtKST: '2026-06-04 16:10 KST',
      sha: '6a12156',
    },
    {
      number: 187,
      title: 'chore(make): add migrate-local for safe local DDL migrate',
      mergedAt: '2026-06-04T05:04:00Z',
      mergedAtKST: '2026-06-04 14:04 KST',
      sha: '75542fc',
    },
    {
      number: 186,
      title: 'fix(ux): surface silent write failures (FRONT-UX-8 + FRONT-UX-7)',
      mergedAt: '2026-06-04T05:03:18Z',
      mergedAtKST: '2026-06-04 14:03 KST',
      sha: '9b581fb',
    },
    {
      number: 185,
      title: 'chore(dashboard): remove state.local.js shadow mechanism',
      mergedAt: '2026-06-04T01:33:59Z',
      mergedAtKST: '2026-06-04 10:33 KST',
      sha: '4cb8a3c',
    },
    {
      number: 184,
      title: 'chore(dashboard): file-roles 15개 추가 (#178/#180/#182 파일)',
      mergedAt: '2026-06-04T00:41:03Z',
      mergedAtKST: '2026-06-04 09:41 KST',
      sha: '80a2067',
    },
    {
      number: 183,
      title: 'docs(backlog): 2026-06-04 Next audit + ID 2축 rename + BM PRD',
      mergedAt: '2026-06-04T00:28:13Z',
      mergedAtKST: '2026-06-04 09:28 KST',
      sha: 'bc8f2f2',
    },
  ],
  agents: [
    {
      name: 'app-test',
      role: 'Pre-push gate — live-browser 3-persona swipe journey + drift check. FULL or FEATURE-SCOPED mode.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'back-maker',
      role: 'Django/DRF backend code — only touches files inside backend/. Runs flake8 after changes.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'code-review',
      role: 'Static code review — integration correctness, API contracts, logic bugs, error handling. Inner loop, per change, pre-commit.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'front-maker',
      role: 'React/Vite frontend code — only touches files inside frontend/. Runs ESLint after changes.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'git-publisher',
      role: 'Edge-case publisher. Mode 3 develop→main deploy + post-deploy develop force-reset + external PR triage + complex rebase + push rejection / mid-merge failure. Routine feature→develop publishes go through git-publish skill (not this agent).',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'security-manager',
      role: 'Security scan — SQL injection, auth bypass, secret leakage, XSS, token storage. Inner loop, per change, pre-commit.',
      model: 'sonnet',
      effort: 'default',
    },
  ],
  fileTree: [
    {
      path: '.agents/skills/browser-verify/SKILL.md',
      role: '브라우저 검증 스킬 정의',
    },
    {
      path: '.agents/skills/git-commit/SKILL.md',
      role: 'git 커밋 스킬 정의',
    },
    {
      path: '.agents/skills/git-publish/SKILL.md',
      role: 'git 퍼블리시 스킬 정의',
    },
    {
      path: '.agents/skills/orchestrate/SKILL.md',
      role: '오케스트레이션 스킬 정의',
    },
    {
      path: '.agents/skills/reporter-inline/SKILL.md',
      role: '감사 기록 스킬 정의',
    },
    {
      path: '.claude/WORKFLOW.md',
      role: 'Claude 워크플로 문서',
    },
    {
      path: '.claude/agents/app-test.md',
      role: 'app-test 에이전트 정의',
    },
    {
      path: '.claude/agents/back-maker.md',
      role: 'back-maker 에이전트 정의',
    },
    {
      path: '.claude/agents/code-review.md',
      role: 'code-review 에이전트 정의',
    },
    {
      path: '.claude/agents/front-maker.md',
      role: 'front-maker 에이전트 정의',
    },
    {
      path: '.claude/agents/git-publisher.md',
      role: 'git-publisher 에이전트 정의',
    },
    {
      path: '.claude/agents/security-manager.md',
      role: 'security-manager 에이전트 정의',
    },
    {
      path: '.claude/plans/2026-06-01-office-recommendation-design.md',
      role: '사무소/architect 추천 설계 플랜 (#178)',
    },
    {
      path: '.claude/plans/2026-06-02-office-save.md',
      role: '사무소 저장 기능 설계 플랜 (#180)',
    },
    {
      path: '.claude/plans/README.md',
      role: '플랜 디렉터리 안내',
    },
    {
      path: '.claude/plans/archive/2026-05-24-merry-toasting-dove.md',
      role: '아카이브 플랜 문서',
    },
    {
      path: '.claude/plans/archive/building-detail-page.md',
      role: '건물 상세 페이지 플랜',
    },
    {
      path: '.claude/plans/archive/perf-trio-optimization.md',
      role: '성능 최적화 플랜',
    },
    {
      path: '.claude/plans/archive/results-page.md',
      role: '결과 페이지 플랜',
    },
    {
      path: '.claude/plans/archive/workflow-skill-absorption.md',
      role: '워크플로 스킬 흡수 플랜',
    },
    {
      path: '.claude/plans/dashboard-autogen-1.md',
      role: '대시보드 자동생성 플랜',
    },
    {
      path: '.claude/plans/profile-harvest-redesign.wf.js',
      role: '프로필 하베스트 재설계 워크플로 스크립트 (#179)',
    },
    {
      path: '.claude/reviews/2026-05-31-swipe-discovery-review.md',
      role: '스와이프 디스커버리 리뷰 기록',
    },
    {
      path: '.claude/skills/git-commit/SKILL.md',
      role: 'git 커밋 스킬 정의',
    },
    {
      path: '.claude/skills/git-publish/SKILL.md',
      role: 'git 퍼블리시 스킬 정의',
    },
    {
      path: '.claude/skills/orchestrate/SKILL.md',
      role: '오케스트레이션 스킬 정의',
    },
    {
      path: '.claude/skills/reporter-inline/SKILL.md',
      role: '감사 기록 스킬 정의',
    },
    {
      path: '.codex/WORKFLOW.md',
      role: 'Codex 워크플로 문서',
    },
    {
      path: '.codex/agents/back-maker.toml',
      role: 'Codex back-maker 설정',
    },
    {
      path: '.codex/agents/code-review.toml',
      role: 'Codex code-review 설정',
    },
    {
      path: '.codex/agents/front-maker.toml',
      role: 'Codex front-maker 설정',
    },
    {
      path: '.codex/agents/git-publisher.toml',
      role: 'Codex git-publisher 설정',
    },
    {
      path: '.codex/agents/security-manager.toml',
      role: 'Codex security-manager 설정',
    },
    {
      path: '.codex/config.toml',
      role: 'Codex 설정',
    },
    {
      path: '.codex/plans/README.md',
      role: 'Codex 플랜 디렉터리 안내',
    },
    {
      path: '.codex/plans/archive/2026-05-24-merry-toasting-dove.md',
      role: 'Codex 아카이브 플랜',
    },
    {
      path: '.codex/plans/archive/building-detail-page.md',
      role: 'Codex 건물 상세 플랜',
    },
    {
      path: '.codex/plans/archive/perf-trio-optimization.md',
      role: '성능 최적화 계획 아카이브',
    },
    {
      path: '.codex/plans/archive/results-page.md',
      role: '결과 페이지 계획 아카이브',
    },
    {
      path: '.codex/plans/archive/workflow-skill-absorption.md',
      role: '워크플로우 스킬 계획 아카이브',
    },
    {
      path: '.github/CODEOWNERS',
      role: '코드 오너 설정',
    },
    {
      path: '.github/PULL_REQUEST_TEMPLATE.md',
      role: 'PR 템플릿',
    },
    {
      path: '.github/workflows/ci.yml',
      role: 'CI 워크플로우 설정',
    },
    {
      path: '.gitignore',
      role: 'git 무시 설정',
    },
    {
      path: 'AGENTS.md',
      role: '에이전트 안내 문서',
    },
    {
      path: 'CLAUDE.md',
      role: 'Claude 프로젝트 지침',
    },
    {
      path: 'CONTRIBUTING.md',
      role: '협업 워크플로우 문서',
    },
    {
      path: 'DESIGN.md',
      role: '디자인 시스템 문서',
    },
    {
      path: 'Makefile',
      role: '빌드 태스크 설정',
    },
    {
      path: 'README.md',
      role: '프로젝트 안내 문서',
    },
    {
      path: 'Task.md',
      role: '태스크 보드 문서',
    },
    {
      path: 'backend/.env.example',
      role: '백엔드 환경변수 예시',
    },
    {
      path: 'backend/apps/__init__.py',
      role: '패키지 init',
    },
    {
      path: 'backend/apps/accounts/__init__.py',
      role: '패키지 init',
    },
    {
      path: 'backend/apps/accounts/apps.py',
      role: 'accounts 앱 설정',
    },
    {
      path: 'backend/apps/accounts/authentication.py',
      role: 'JWT 유저 캐시 인증',
    },
    {
      path: 'backend/apps/accounts/jwt_serializers.py',
      role: 'JWT 토큰 직렬화기',
    },
    {
      path: 'backend/apps/accounts/migrations/0001_initial.py',
      role: 'DB 마이그레이션 초기',
    },
    {
      path: 'backend/apps/accounts/migrations/0002_userprofile_phase13_extension.py',
      role: 'DB 마이그레이션 Phase13 확장',
    },
    {
      path: 'backend/apps/accounts/migrations/0003_userprofile_font_userprofile_theme.py',
      role: 'DB 마이그레이션 테마/폰트',
    },
    {
      path: 'backend/apps/accounts/migrations/0004_userprofile_guest_onboarding_consent.py',
      role: 'DB 마이그레이션 게스트 온보딩',
    },
    {
      path: 'backend/apps/accounts/migrations/0005_userprofile_liked_building_ids.py',
      role: 'DB 마이그레이션 좋아요 건물',
    },
    {
      path: 'backend/apps/accounts/migrations/__init__.py',
      role: '패키지 init',
    },
    {
      path: 'backend/apps/accounts/models.py',
      role: 'UserProfile 모델',
    },
    {
      path: 'backend/apps/accounts/permissions.py',
      role: '게스트 차단 권한',
    },
    {
      path: 'backend/apps/accounts/serializers.py',
      role: '유저 프로필 직렬화기',
    },
    {
      path: 'backend/apps/accounts/signals.py',
      role: '유저 캐시 무효화 시그널',
    },
    {
      path: 'backend/apps/accounts/tests/__init__.py',
      role: '패키지 init',
    },
    {
      path: 'backend/apps/accounts/tests/conftest.py',
      role: 'accounts 테스트 픽스처',
    },
    {
      path: 'backend/apps/accounts/tests/test_liked_buildings.py',
      role: '좋아요 건물 테스트',
    },
    {
      path: 'backend/apps/accounts/tests/test_phase13_userprofile.py',
      role: 'UserProfile Phase13 테스트',
    },
    {
      path: 'backend/apps/accounts/tests/test_theme_font.py',
      role: '테마·폰트 설정 테스트',
    },
    {
      path: 'backend/apps/accounts/tests/test_userserializer.py',
      role: 'UserSerializer 테스트',
    },
    {
      path: 'backend/apps/accounts/throttling.py',
      role: '게스트 인증 throttle 클래스',
    },
    {
      path: 'backend/apps/accounts/urls.py',
      role: 'accounts 인증·프로필 URL 라우팅',
    },
    {
      path: 'backend/apps/accounts/views/__init__.py',
      role: 'accounts.views facade 재노출',
    },
    {
      path: 'backend/apps/accounts/views/auth.py',
      role: '소셜·게스트 로그인 인증 뷰',
    },
    {
      path: 'backend/apps/accounts/views/profile.py',
      role: '유저 프로필·좋아요 건물 뷰',
    },
    {
      path: 'backend/apps/profiles/__init__.py',
      role: 'profiles 패키지 init',
    },
    {
      path: 'backend/apps/profiles/apps.py',
      role: 'profiles 앱 설정',
    },
    {
      path: 'backend/apps/profiles/management/__init__.py',
      role: 'profiles management 패키지 init',
    },
    {
      path: 'backend/apps/profiles/management/commands/__init__.py',
      role: 'profiles management commands 패키지 init',
    },
    {
      path: 'backend/apps/profiles/management/commands/sync_offices.py',
      role: 'canonical_v2_architects(is_recommendable) → Office 테이블 싱크 명령 (#180)',
    },
    {
      path: 'backend/apps/profiles/migrations/0001_initial.py',
      role: 'DB 마이그레이션 (Office 초기)',
    },
    {
      path: 'backend/apps/profiles/migrations/0002_alter_officeprojectlink_confidence.py',
      role: 'DB 마이그레이션 (confidence 변경)',
    },
    {
      path: 'backend/apps/profiles/migrations/0003_office_is_recommendable_office_primary_city_and_more.py',
      role: 'Office is_recommendable/primary_city + SavedOffice 마이그레이션 (#180)',
    },
    {
      path: 'backend/apps/profiles/migrations/0004_alter_office_canonical_id.py',
      role: 'Office.canonical_id TextField unique 마이그레이션 (#180)',
    },
    {
      path: 'backend/apps/profiles/migrations/0005_delete_savedoffice.py',
      role: '',
    },
    {
      path: 'backend/apps/profiles/migrations/__init__.py',
      role: '마이그레이션 패키지 init',
    },
    {
      path: 'backend/apps/profiles/models.py',
      role: 'Office·프로젝트링크 모델',
    },
    {
      path: 'backend/apps/profiles/serializers.py',
      role: 'Office 직렬화·클레임 시리얼라이저',
    },
    {
      path: 'backend/apps/profiles/tests/__init__.py',
      role: 'profiles 테스트 패키지 init',
    },
    {
      path: 'backend/apps/profiles/tests/conftest.py',
      role: 'profiles 테스트 fixture 설정',
    },
    {
      path: 'backend/apps/profiles/tests/test_phase13_office.py',
      role: 'Office 클레임 플로우 테스트',
    },
    {
      path: 'backend/apps/profiles/throttles.py',
      role: 'Office 클레임 throttle 클래스',
    },
    {
      path: 'backend/apps/profiles/urls.py',
      role: 'Office·클레임 URL 라우팅',
    },
    {
      path: 'backend/apps/profiles/views.py',
      role: 'Office 상세·클레임·관리 뷰',
    },
    {
      path: 'backend/apps/recommendation/__init__.py',
      role: 'recommendation 패키지 init',
    },
    {
      path: 'backend/apps/recommendation/apps.py',
      role: 'recommendation 앱 설정',
    },
    {
      path: 'backend/apps/recommendation/caches.py',
      role: '추천 TTL 캐시 헬퍼',
    },
    {
      path: 'backend/apps/recommendation/engine.py',
      role: '추천 엔진 핵심',
    },
    {
      path: 'backend/apps/recommendation/engine_cards.py',
      role: '건물 카드 변환 헬퍼',
    },
    {
      path: 'backend/apps/recommendation/engine_convergence.py',
      role: '수렴·신뢰도 수학',
    },
    {
      path: 'backend/apps/recommendation/engine_filters.py',
      role: '필터 SQL 빌더',
    },
    {
      path: 'backend/apps/recommendation/engine_vecmath.py',
      role: '벡터 수학 헬퍼',
    },
    {
      path: 'backend/apps/recommendation/event_log.py',
      role: '세션 이벤트 로깅 헬퍼',
    },
    {
      path: 'backend/apps/recommendation/management/__init__.py',
      role: 'management 패키지 init',
    },
    {
      path: 'backend/apps/recommendation/management/commands/__init__.py',
      role: 'commands 패키지 init',
    },
    {
      path: 'backend/apps/recommendation/management/commands/purge_legacy_projects.py',
      role: '레거시 프로젝트 정리 커맨드',
    },
    {
      path: 'backend/apps/recommendation/migrations/0001_initial.py',
      role: 'DB 마이그레이션 (추천 초기)',
    },
    {
      path: 'backend/apps/recommendation/migrations/0002_analysissession_initial_batch.py',
      role: 'DB 마이그레이션 (initial_batch 추가)',
    },
    {
      path: 'backend/apps/recommendation/migrations/0003_analysissession_convergence_history_and_more.py',
      role: 'DB 마이그레이션 0003 수렴 이력 필드',
    },
    {
      path: 'backend/apps/recommendation/migrations/0004_analysissession_pool_scores.py',
      role: 'DB 마이그레이션 0004 풀 점수 필드',
    },
    {
      path: 'backend/apps/recommendation/migrations/0005_project_report_image.py',
      role: 'DB 마이그레이션 0005 리포트 이미지 필드',
    },
    {
      path: 'backend/apps/recommendation/migrations/0006_remove_total_rounds_and_scope_idempotency.py',
      role: 'DB 마이그레이션 0006 멱등성 스코프',
    },
    {
      path: 'backend/apps/recommendation/migrations/0007_project_saved_ids_and_liked_intensity.py',
      role: 'DB 마이그레이션 0007 북마크·좋아요 강도',
    },
    {
      path: 'backend/apps/recommendation/migrations/0008_analysissession_pool_relaxation_state.py',
      role: 'DB 마이그레이션 0008 풀 완화 상태',
    },
    {
      path: 'backend/apps/recommendation/migrations/0009_sessionevent.py',
      role: 'DB 마이그레이션 0009 세션 이벤트 모델',
    },
    {
      path: 'backend/apps/recommendation/migrations/0010_alter_sessionevent_event_type.py',
      role: 'DB 마이그레이션 0010 이벤트 타입 변경',
    },
    {
      path: 'backend/apps/recommendation/migrations/0011_add_hyde_topic03.py',
      role: 'DB 마이그레이션 0011 HyDE Topic03',
    },
    {
      path: 'backend/apps/recommendation/migrations/0012_add_topic01_q_text.py',
      role: 'DB 마이그레이션 0012 Topic01 q_text',
    },
    {
      path: 'backend/apps/recommendation/migrations/0013_imp10_topic06_telemetry.py',
      role: 'DB 마이그레이션 0013 IMP10 텔레메트리',
    },
    {
      path: 'backend/apps/recommendation/migrations/0014_add_stage2_timing_event_type.py',
      role: 'DB 마이그레이션 0014 Stage2 타이밍 이벤트',
    },
    {
      path: 'backend/apps/recommendation/migrations/0015_project_visibility_reaction_count.py',
      role: 'DB 마이그레이션 0015 공개여부·반응수',
    },
    {
      path: 'backend/apps/recommendation/migrations/0016_alter_sessionevent_event_type.py',
      role: 'DB 마이그레이션 0016 이벤트 타입 변경',
    },
    {
      path: 'backend/apps/recommendation/migrations/0017_add_extended_rounds.py',
      role: 'DB 마이그레이션 0017 연장 라운드 필드',
    },
    {
      path: 'backend/apps/recommendation/migrations/0018_rename_swipeevent_canonical_bld_id.py',
      role: 'DB 마이그레이션 0018 스와이프 필드명 변경',
    },
    {
      path: 'backend/apps/recommendation/migrations/0019_normalize_legacy_entry_shapes.py',
      role: 'DB 마이그레이션 0019 레거시 엔트리 정규화',
    },
    {
      path: 'backend/apps/recommendation/migrations/0020_question_card_fields.py',
      role: 'DB 마이그레이션 0020 질문 카드 필드',
    },
    {
      path: 'backend/apps/recommendation/migrations/__init__.py',
      role: '마이그레이션 패키지 init',
    },
    {
      path: 'backend/apps/recommendation/models.py',
      role: 'Project·세션 ORM 모델',
    },
    {
      path: 'backend/apps/recommendation/perf_timing.py',
      role: '단계별 성능 타이밍 계측',
    },
    {
      path: 'backend/apps/recommendation/serializers.py',
      role: 'Project 보드 직렬화기',
    },
    {
      path: 'backend/apps/recommendation/services/__init__.py',
      role: 'services 패키지 facade',
    },
    {
      path: 'backend/apps/recommendation/services/_caches.py',
      role: 'Gemini·V_initial 캐시 헬퍼',
    },
    {
      path: 'backend/apps/recommendation/services/_gemini.py',
      role: 'Gemini 클라이언트·재시도 래퍼',
    },
    {
      path: 'backend/apps/recommendation/services/_prompts.py',
      role: '파싱 프롬프트·어휘 상수',
    },
    {
      path: 'backend/apps/recommendation/services/embeddings.py',
      role: 'HuggingFace 임베딩 호출',
    },
    {
      path: 'backend/apps/recommendation/services/generation.py',
      role: 'Gemini 페르소나·비주얼 생성',
    },
    {
      path: 'backend/apps/recommendation/services/parse_query.py',
      role: 'Gemini 쿼리 파싱 서비스',
    },
    {
      path: 'backend/apps/recommendation/services/rerank.py',
      role: 'Gemini 셋와이즈 리랭크',
    },
    {
      path: 'backend/apps/recommendation/services/session_service.py',
      role: '세션 생성·결과 오케스트레이션',
    },
    {
      path: 'backend/apps/recommendation/services/swipe_service.py',
      role: '스와이프·질문카드 오케스트레이션',
    },
    {
      path: 'backend/apps/recommendation/tests/__init__.py',
      role: '테스트 패키지 init',
    },
    {
      path: 'backend/apps/recommendation/tests/conftest.py',
      role: 'recommendation 테스트 픽스처',
    },
    {
      path: 'backend/apps/recommendation/tests/test_discovery.py',
      role: 'Discovery 피드 테스트',
    },
    {
      path: 'backend/apps/recommendation/tests/test_phase13_board.py',
      role: 'Phase13 보드 테스트',
    },
    {
      path: 'backend/apps/recommendation/tests/test_row_to_card.py',
      role: 'row_to_card 변환 테스트',
    },
    {
      path: 'backend/apps/recommendation/urls.py',
      role: '추천 API URL 라우팅',
    },
    {
      path: 'backend/apps/recommendation/views/__init__.py',
      role: 'views facade 재노출',
    },
    {
      path: 'backend/apps/recommendation/views/_shared.py',
      role: '뷰 공용 헬퍼',
    },
    {
      path: 'backend/apps/recommendation/views/discovery.py',
      role: 'Discovery 피드 뷰',
    },
    {
      path: 'backend/apps/recommendation/views/office_recommendation.py',
      role: 'architect 추천/상세/팔로우 뷰 (#178/#182)',
    },
    {
      path: 'backend/apps/recommendation/views/projects.py',
      role: '프로젝트 CRUD 뷰',
    },
    {
      path: 'backend/apps/recommendation/views/reports.py',
      role: '페르소나 리포트 뷰',
    },
    {
      path: 'backend/apps/recommendation/views/search.py',
      role: '쿼리 파싱 검색 뷰',
    },
    {
      path: 'backend/apps/recommendation/views/sessions.py',
      role: '분석 세션 뷰',
    },
    {
      path: 'backend/apps/recommendation/views/swipe.py',
      role: '스와이프 처리 뷰',
    },
    {
      path: 'backend/apps/recommendation/views/telemetry.py',
      role: '이미지 로드 텔레메트리 뷰',
    },
    {
      path: 'backend/apps/social/__init__.py',
      role: '패키지 init',
    },
    {
      path: 'backend/apps/social/apps.py',
      role: 'social 앱 설정',
    },
    {
      path: 'backend/apps/social/migrations/0001_initial.py',
      role: 'DB 마이그레이션 초기 스키마',
    },
    {
      path: 'backend/apps/social/migrations/0002_rename_social_foll_followee_idx_social_foll_followe_0eabb0_idx_and_more.py',
      role: 'DB 마이그레이션 follow 인덱스 변경',
    },
    {
      path: 'backend/apps/social/migrations/0003_reaction.py',
      role: 'DB 마이그레이션 Reaction',
    },
    {
      path: 'backend/apps/social/migrations/0004_officefollow.py',
      role: 'DB 마이그레이션 OfficeFollow',
    },
    {
      path: 'backend/apps/social/migrations/0005_architectfollow.py',
      role: 'ArchitectFollow 모델 마이그레이션 (#182)',
    },
    {
      path: 'backend/apps/social/migrations/0006_delete_officefollow.py',
      role: '',
    },
    {
      path: 'backend/apps/social/migrations/__init__.py',
      role: '패키지 init',
    },
    {
      path: 'backend/apps/social/models.py',
      role: '팔로우/리액션 모델',
    },
    {
      path: 'backend/apps/social/serializers.py',
      role: 'social 직렬화기 재노출',
    },
    {
      path: 'backend/apps/social/tests/__init__.py',
      role: '패키지 init',
    },
    {
      path: 'backend/apps/social/tests/conftest.py',
      role: 'social 테스트 픽스처',
    },
    {
      path: 'backend/apps/social/tests/test_follow.py',
      role: '유저 팔로우 테스트',
    },
    {
      path: 'backend/apps/social/tests/test_reaction.py',
      role: '프로젝트 리액션 테스트',
    },
    {
      path: 'backend/apps/social/urls.py',
      role: 'social API URL 라우팅',
    },
    {
      path: 'backend/apps/social/views.py',
      role: '팔로우/리액션 뷰',
    },
    {
      path: 'backend/config/__init__.py',
      role: '패키지 init',
    },
    {
      path: 'backend/config/db_router.py',
      role: '멀티 DB 라우터',
    },
    {
      path: 'backend/config/settings.py',
      role: 'Django 프로젝트 설정',
    },
    {
      path: 'backend/config/urls.py',
      role: '루트 URL 라우팅',
    },
    {
      path: 'backend/config/wsgi.py',
      role: 'WSGI 진입점',
    },
    {
      path: 'backend/conftest.py',
      role: 'pytest 루트 픽스처 설정',
    },
    {
      path: 'backend/manage.py',
      role: 'Django 관리 명령 진입점',
    },
    {
      path: 'backend/pytest.ini',
      role: 'pytest 설정',
    },
    {
      path: 'backend/railway.toml',
      role: 'Railway 배포 설정',
    },
    {
      path: 'backend/requirements-dev.txt',
      role: '개발 의존성 설정',
    },
    {
      path: 'backend/requirements.txt',
      role: '런타임 의존성 설정',
    },
    {
      path: 'backend/tests/__init__.py',
      role: '테스트 패키지 init',
    },
    {
      path: 'backend/tests/conftest.py',
      role: '테스트 공용 픽스처 설정',
    },
    {
      path: 'backend/tests/test_auth.py',
      role: '인증 테스트',
    },
    {
      path: 'backend/tests/test_back_llm1_required_slate.py',
      role: 'LLM 필수 슬레이트 테스트',
    },
    {
      path: 'backend/tests/test_board_detail_perf.py',
      role: '보드 상세 성능 테스트',
    },
    {
      path: 'backend/tests/test_bookmark.py',
      role: '북마크 테스트',
    },
    {
      path: 'backend/tests/test_cache_backend.py',
      role: '캐시 백엔드 테스트',
    },
    {
      path: 'backend/tests/test_chat_phase.py',
      role: '채팅 단계 테스트',
    },
    {
      path: 'backend/tests/test_confidence.py',
      role: '신뢰도 테스트',
    },
    {
      path: 'backend/tests/test_discovery_perf.py',
      role: '디스커버리 성능 테스트',
    },
    {
      path: 'backend/tests/test_discovery_taste_cache.py',
      role: '디스커버리 취향 캐시 테스트',
    },
    {
      path: 'backend/tests/test_dpp_overfetch.py',
      role: 'DPP 오버페치 테스트',
    },
    {
      path: 'backend/tests/test_engine_filter_hard_constraint.py',
      role: '엔진 하드 제약 필터 테스트',
    },
    {
      path: 'backend/tests/test_gemini_fail_fast.py',
      role: 'Gemini fail-fast 테스트',
    },
    {
      path: 'backend/tests/test_gemini_timeout.py',
      role: 'Gemini 타임아웃 테스트',
    },
    {
      path: 'backend/tests/test_get_diverse_random_random.py',
      role: '다양성 랜덤 추출 테스트',
    },
    {
      path: 'backend/tests/test_get_top_k_no_pref_order.py',
      role: 'top-k 무선호 순서 테스트',
    },
    {
      path: 'backend/tests/test_guest_auth.py',
      role: '게스트 인증 테스트',
    },
    {
      path: 'backend/tests/test_hybrid_retrieval.py',
      role: '하이브리드 검색 테스트',
    },
    {
      path: 'backend/tests/test_hyde.py',
      role: 'HyDE 검색 테스트',
    },
    {
      path: 'backend/tests/test_image_hosting_fallback.py',
      role: '이미지 호스팅 폴백 테스트',
    },
    {
      path: 'backend/tests/test_imp10_topic06_telemetry.py',
      role: 'IMP10 텔레메트리 테스트',
    },
    {
      path: 'backend/tests/test_imp5_context_caching.py',
      role: 'IMP5 컨텍스트 캐싱 테스트',
    },
    {
      path: 'backend/tests/test_imp6_late_binding_plumbing.py',
      role: 'IMP6 지연 바인딩 테스트',
    },
    {
      path: 'backend/tests/test_imp6_stage_decouple.py',
      role: 'IMP6 스테이지 분리 테스트',
    },
    {
      path: 'backend/tests/test_imp7_pool_cache.py',
      role: 'IMP7 풀 캐시 테스트',
    },
    {
      path: 'backend/tests/test_imp8_async_prefetch.py',
      role: 'IMP8 비동기 프리페치 테스트',
    },
    {
      path: 'backend/tests/test_jwt_cache.py',
      role: 'JWT 캐시 테스트',
    },
    {
      path: 'backend/tests/test_jwt_refresh_blacklist.py',
      role: 'JWT 리프레시 블랙리스트 테스트',
    },
    {
      path: 'backend/tests/test_m1_clarification_cap.py',
      role: 'M1 질문 카드 상한 테스트',
    },
    {
      path: 'backend/tests/test_m4_clarification_telemetry.py',
      role: 'M4 질문 카드 텔레메트리 테스트',
    },
    {
      path: 'backend/tests/test_migrations_legacy_entries.py',
      role: '레거시 마이그레이션 항목 테스트',
    },
    {
      path: 'backend/tests/test_profile_perf.py',
      role: '프로필 성능 테스트',
    },
    {
      path: 'backend/tests/test_projects.py',
      role: '프로젝트 API 테스트',
    },
    {
      path: 'backend/tests/test_projects_n_plus_one.py',
      role: '프로젝트 N+1 쿼리 테스트',
    },
    {
      path: 'backend/tests/test_rerank_shape.py',
      role: '리랭크 결과 형태 테스트',
    },
    {
      path: 'backend/tests/test_schema_robustness.py',
      role: '스키마 견고성 테스트',
    },
    {
      path: 'backend/tests/test_session_create_correctness.py',
      role: '세션 생성 정확성 테스트',
    },
    {
      path: 'backend/tests/test_session_create_dedupe.py',
      role: '세션 생성 중복 제거 테스트',
    },
    {
      path: 'backend/tests/test_sessions.py',
      role: '세션 API 테스트',
    },
    {
      path: 'backend/tests/test_swipe.py',
      role: '스와이프 처리 테스트',
    },
    {
      path: 'backend/tests/test_swipe_goal.py',
      role: '스와이프 목표 달성 테스트',
    },
    {
      path: 'backend/tests/test_topic02.py',
      role: '토픽02 추천 테스트',
    },
    {
      path: 'backend/tests/test_topic04.py',
      role: '토픽04 추천 테스트',
    },
    {
      path: 'backend/tests/test_topic06.py',
      role: '토픽06 추천 테스트',
    },
    {
      path: 'backend/tests/test_topic_composition.py',
      role: '토픽 구성 테스트',
    },
    {
      path: 'backend/tools/perf_measure.py',
      role: '엔드포인트 지연 측정 도구',
    },
    {
      path: 'docs/COLLAB_HANDOFF.md',
      role: '협업 인수인계 문서',
    },
    {
      path: 'docs/MAKEWEB_DB_SWAP_RESPONSE.md',
      role: 'DB 교체 대응 문서',
    },
    {
      path: 'docs/algorithm.md',
      role: '추천 알고리즘 레퍼런스 문서',
    },
    {
      path: 'docs/database-schema.md',
      role: 'DB 스키마 문서',
    },
    {
      path: 'docs/prd/archibe-business-model.html',
      role: 'archibe 비즈니스 모델 PRD (정적 HTML)',
    },
    {
      path: 'docs/specs/architect-unification.md',
      role: '',
    },
    {
      path: 'frontend/.env.example',
      role: '프론트 환경변수 예시 설정',
    },
    {
      path: 'frontend/.gitignore',
      role: '프론트 Git 무시 설정',
    },
    {
      path: 'frontend/eslint.config.js',
      role: 'ESLint 설정',
    },
    {
      path: 'frontend/index.html',
      role: 'Vite 진입 HTML',
    },
    {
      path: 'frontend/package-lock.json',
      role: '의존성 잠금 파일',
    },
    {
      path: 'frontend/package.json',
      role: '프론트 패키지 매니페스트',
    },
    {
      path: 'frontend/public/favicon.svg',
      role: '파비콘 에셋',
    },
    {
      path: 'frontend/src/App.jsx',
      role: '앱 루트 라우팅 컴포넌트',
    },
    {
      path: 'frontend/src/api/architects.js',
      role: 'architect 추천/프로필/팔로우/saved studios API 래퍼 (#178/#182)',
    },
    {
      path: 'frontend/src/api/auth.js',
      role: '인증 API 클라이언트',
    },
    {
      path: 'frontend/src/api/client.js',
      role: 'API 클라이언트 facade',
    },
    {
      path: 'frontend/src/api/core.js',
      role: 'JWT 토큰·fetch 코어',
    },
    {
      path: 'frontend/src/api/discovery.js',
      role: '디스커버리 피드 API 클라이언트',
    },
    {
      path: 'frontend/src/api/images.js',
      role: '이미지 카드 정규화·텔레메트리 헬퍼',
    },
    {
      path: 'frontend/src/api/liked.js',
      role: '좋아요 건물 API 클라이언트',
    },
    {
      path: 'frontend/src/api/profiles.js',
      role: '사무소·유저 프로필 API 클라이언트',
    },
    {
      path: 'frontend/src/api/projects.js',
      role: '프로젝트·보드 CRUD API 클라이언트',
    },
    {
      path: 'frontend/src/api/sessions.js',
      role: '분석 세션·스와이프 API 클라이언트',
    },
    {
      path: 'frontend/src/api/social.js',
      role: '팔로우·리액션 소셜 API 클라이언트',
    },
    {
      path: 'frontend/src/components/AppearanceSettings.jsx',
      role: '테마·폰트 설정 UI',
    },
    {
      path: 'frontend/src/components/DebugOverlay.jsx',
      role: '세션·스와이프 디버그 오버레이',
    },
    {
      path: 'frontend/src/components/EditProfileModal.jsx',
      role: '프로필 편집 모달',
    },
    {
      path: 'frontend/src/components/ErrorBoundary.jsx',
      role: '에러 바운더리 컴포넌트',
    },
    {
      path: 'frontend/src/components/GoogleLoginButton.jsx',
      role: '구글 로그인 버튼',
    },
    {
      path: 'frontend/src/components/GoogleVerifyButton.jsx',
      role: '구글 계정 인증 버튼',
    },
    {
      path: 'frontend/src/components/LLMSearchUpdateWrapper.jsx',
      role: 'LLM 검색 업데이트 모드 래퍼',
    },
    {
      path: 'frontend/src/components/ProtectedRoute.jsx',
      role: '인증 보호 라우트 가드',
    },
    {
      path: 'frontend/src/components/QuestionCard.jsx',
      role: '취향 보정 질문 카드',
    },
    {
      path: 'frontend/src/components/SaveToBoardModal.jsx',
      role: '보드 저장 모달',
    },
    {
      path: 'frontend/src/components/ShareCardModal.jsx',
      role: '프로필 명함 공유 모달',
    },
    {
      path: 'frontend/src/components/SurpriseBoardModal.jsx',
      role: '큐레이션 보드 제안 모달',
    },
    {
      path: 'frontend/src/components/SwipeCard.jsx',
      role: '스와이프 카드 컴포넌트',
    },
    {
      path: 'frontend/src/components/SwipeGestureFrame.jsx',
      role: '공통 swipe 제스처 래퍼',
    },
    {
      path: 'frontend/src/components/TabBar.jsx',
      role: '하단 탭바 내비게이션',
    },
    {
      path: 'frontend/src/components/TutorialPopup.jsx',
      role: '스와이프 튜토리얼 팝업',
    },
    {
      path: 'frontend/src/components/VerifyGateModal.jsx',
      role: '보드 한도 인증 게이트 모달',
    },
    {
      path: 'frontend/src/components/icons.jsx',
      role: '공통 stroke 아이콘 세트',
    },
    {
      path: 'frontend/src/components/profile/ArticleCard.jsx',
      role: '프로필 아티클 카드',
    },
    {
      path: 'frontend/src/components/profile/BioPersonaFlipCard.jsx',
      role: '바이오·페르소나 플립 카드',
    },
    {
      path: 'frontend/src/components/profile/BoardCard.jsx',
      role: '프로필 보드 플립 카드',
    },
    {
      path: 'frontend/src/components/profile/BusinessCard.jsx',
      role: '프로필 명함 카드(3D 플립)',
    },
    {
      path: 'frontend/src/components/profile/DescriptionAboutFlipCard.jsx',
      role: '사무소 소개 플립 카드',
    },
    {
      path: 'frontend/src/components/profile/EditCardForm.jsx',
      role: '프로필 편집 폼',
    },
    {
      path: 'frontend/src/components/profile/EditCardForm.module.css',
      role: '프로필 편집 폼 스타일',
    },
    {
      path: 'frontend/src/components/profile/FakeQr.jsx',
      role: '공유 명함 스텁 QR',
    },
    {
      path: 'frontend/src/components/profile/FollowList.jsx',
      role: '팔로워·팔로잉 리스트',
    },
    {
      path: 'frontend/src/components/profile/FollowList.module.css',
      role: '팔로우 리스트 스타일',
    },
    {
      path: 'frontend/src/components/profile/FollowListModal.jsx',
      role: '팔로워·팔로잉 인스타식 팝업',
    },
    {
      path: 'frontend/src/components/profile/InfoCol.jsx',
      role: '카드 정보 컬럼 프리미티브',
    },
    {
      path: 'frontend/src/components/profile/ProjectCard.jsx',
      role: '사무소 프로젝트 카드',
    },
    {
      path: 'frontend/src/components/swipeGestureConfig.js',
      role: 'swipe 제스처 설정 상수',
    },
    {
      path: 'frontend/src/context/ThemeContext.jsx',
      role: '테마·폰트 Provider',
    },
    {
      path: 'frontend/src/context/_themeContext.js',
      role: '테마 React context 정의',
    },
    {
      path: 'frontend/src/hooks/useBoard.js',
      role: '보드 상세 로딩 훅',
    },
    {
      path: 'frontend/src/hooks/useFollowList.js',
      role: '팔로워·팔로잉 페이지네이션 훅',
    },
    {
      path: 'frontend/src/hooks/useImageTelemetry.js',
      role: '이미지 로드 텔레메트리 훅',
    },
    {
      path: 'frontend/src/hooks/useProjectReactors.js',
      role: '프로젝트 리액터 페이지네이션 훅',
    },
    {
      path: 'frontend/src/hooks/useResults.js',
      role: '세션 결과·북마크 훅',
    },
    {
      path: 'frontend/src/hooks/useTheme.js',
      role: '테마 context 소비 훅',
    },
    {
      path: 'frontend/src/index.css',
      role: '전역 기본 스타일',
    },
    {
      path: 'frontend/src/layouts/MainLayout.jsx',
      role: '메인 레이아웃 + TabBar 셸',
    },
    {
      path: 'frontend/src/main.jsx',
      role: 'React 앱 진입점',
    },
    {
      path: 'frontend/src/pages/ArchitectProfilePage.jsx',
      role: 'architect 프로필 페이지 (#182)',
    },
    {
      path: 'frontend/src/pages/ArchitectProfilePage.module.css',
      role: 'architect 프로필 페이지 CSS 모듈 (#182)',
    },
    {
      path: 'frontend/src/pages/BoardDetailPage.jsx',
      role: '보드 상세 페이지',
    },
    {
      path: 'frontend/src/pages/BuildingDetailPage.jsx',
      role: '건물 상세 페이지',
    },
    {
      path: 'frontend/src/pages/DiscoveryPage.jsx',
      role: '디스커버리 스와이프 피드',
    },
    {
      path: 'frontend/src/pages/FirmProfilePage.jsx',
      role: '사무소 프로필 페이지',
    },
    {
      path: 'frontend/src/pages/LLMSearchPage.jsx',
      role: 'LLM 검색 페이지',
    },
    {
      path: 'frontend/src/pages/LikedProjectsPage.jsx',
      role: '좋아요 건물 그리드 페이지',
    },
    {
      path: 'frontend/src/pages/LoginPage.jsx',
      role: '게스트 온보딩 로그인 페이지',
    },
    {
      path: 'frontend/src/pages/ProjectSetupPage.jsx',
      role: '프로젝트 생성 설정 페이지',
    },
    {
      path: 'frontend/src/pages/ResultsPage.jsx',
      role: '추천 결과 페이지',
    },
    {
      path: 'frontend/src/pages/SwipePage.jsx',
      role: '취향 분석 스와이프 페이지',
    },
    {
      path: 'frontend/src/pages/UserProfilePage.jsx',
      role: '유저 프로필 페이지',
    },
    {
      path: 'frontend/src/pages/boardDetail/ArchitectSection.jsx',
      role: '보드 상세 architect 추천 섹션 (#178)',
    },
    {
      path: 'frontend/src/pages/boardDetail/ArchitectSection.module.css',
      role: '보드 상세 architect 섹션 CSS 모듈 (#178)',
    },
    {
      path: 'frontend/src/pages/boardDetail/BuildingTile.jsx',
      role: '보드 건물 타일 카드',
    },
    {
      path: 'frontend/src/pages/boardDetail/RecommendedTile.jsx',
      role: '보드 추천 타일 카드',
    },
    {
      path: 'frontend/src/pages/buildingDetail/ErrorState.jsx',
      role: '건물 상세 에러 상태',
    },
    {
      path: 'frontend/src/pages/buildingDetail/Header.jsx',
      role: '건물 상세 헤더 바',
    },
    {
      path: 'frontend/src/pages/buildingDetail/LoadingState.jsx',
      role: '건물 상세 로딩 상태',
    },
    {
      path: 'frontend/src/pages/buildingDetail/helpers.js',
      role: '건물 상세 메타 헬퍼',
    },
    {
      path: 'frontend/src/pages/firmProfile/FirmArticlesSection.jsx',
      role: '사무소 아티클 섹션',
    },
    {
      path: 'frontend/src/pages/firmProfile/FirmProfileHeader.jsx',
      role: '사무소 프로필 헤더 바',
    },
    {
      path: 'frontend/src/pages/firmProfile/FirmProfileHero.jsx',
      role: '사무소 프로필 히어로',
    },
    {
      path: 'frontend/src/pages/firmProfile/FirmProjectsSection.jsx',
      role: '사무소 프로젝트 섹션',
    },
    {
      path: 'frontend/src/pages/userProfile/BoardGrid.jsx',
      role: '프로필 보드 그리드',
    },
    {
      path: 'frontend/src/pages/userProfile/FollowListPage.jsx',
      role: '팔로워·팔로잉 deep-link 페이지',
    },
    {
      path: 'frontend/src/pages/userProfile/ProfileHeader.jsx',
      role: '유저 프로필 헤더 바',
    },
    {
      path: 'frontend/src/pages/userProfile/ProfileHero.jsx',
      role: '유저 프로필 히어로',
    },
    {
      path: 'frontend/src/tokens.css',
      role: '디자인 토큰 CSS 변수',
    },
    {
      path: 'frontend/src/utils/appHelpers.js',
      role: '앱 필터·에러 헬퍼',
    },
    {
      path: 'frontend/src/utils/loginFlow.js',
      role: '게스트 온보딩 유틸',
    },
    {
      path: 'frontend/src/utils/loginFlow.test.mjs',
      role: 'loginFlow 테스트',
    },
    {
      path: 'frontend/src/utils/reportWriteError.js',
      role: '',
    },
    {
      path: 'frontend/src/utils/resolveProjectBackendId.js',
      role: '프로젝트 백엔드 ID 해석 유틸',
    },
    {
      path: 'frontend/vercel.json',
      role: 'Vercel 배포 설정',
    },
    {
      path: 'frontend/vite.config.js',
      role: 'Vite 빌드 설정',
    },
    {
      path: 'hooks/pre-push',
      role: '마이그레이션 번호 충돌 검사 훅',
    },
    {
      path: 'project/dashboard.html',
      role: '프로젝트 상태 대시보드 페이지',
    },
    {
      path: 'project/file-roles.json',
      role: '파일트리 role 설명 맵',
    },
    {
      path: 'project/mermaid.min.js',
      role: 'Mermaid 다이어그램 번들',
    },
    {
      path: 'project/state.js',
      role: '대시보드 상태 데이터',
    },
    {
      path: 'tools/.smoke.sh',
      role: 'git 스크립트 환경 스모크 검사',
    },
    {
      path: 'tools/back-validate.sh',
      role: '백엔드 검증 체인 스크립트',
    },
    {
      path: 'tools/check-frontend.sh',
      role: '프론트 lint+빌드 래퍼',
    },
    {
      path: 'tools/front-validate.sh',
      role: '프론트 검증 체인 스크립트',
    },
    {
      path: 'tools/gen-state.js',
      role: 'state.js 생성 스크립트',
    },
    {
      path: 'tools/git-new-feature.sh',
      role: '피처 브랜치 생성 스크립트',
    },
    {
      path: 'tools/git-poll-merge.sh',
      role: 'PR CI 폴링 스크립트',
    },
    {
      path: 'tools/git-push-pr.sh',
      role: '브랜치 푸시+PR 생성 스크립트',
    },
    {
      path: 'tools/git-stage-and-commit.sh',
      role: '안전 커밋 스크립트',
    },
    {
      path: 'tools/install-hooks.sh',
      role: 'git 훅 설치 스크립트',
    },
    {
      path: 'tools/migrate.sh',
      role: '마이그레이션 적용 스크립트',
    },
    {
      path: 'tools/onboarding.sh',
      role: '협업자 온보딩 스크립트',
    },
    {
      path: 'tools/test-backend.sh',
      role: 'pytest 래퍼 스크립트',
    },
    {
      path: 'web-testing/AGENTS.md',
      role: '테스트 러너 에이전트 가이드',
    },
    {
      path: 'web-testing/dashboard/app.js',
      role: 'E2E 테스트 대시보드 SPA',
    },
    {
      path: 'web-testing/dashboard/index.html',
      role: '테스트 대시보드 페이지',
    },
    {
      path: 'web-testing/dashboard/style.css',
      role: '테스트 대시보드 스타일',
    },
    {
      path: 'web-testing/requirements.txt',
      role: '테스트 의존성 설정',
    },
    {
      path: 'web-testing/research/__init__.py',
      role: 'research 패키지 init',
    },
    {
      path: 'web-testing/research/persona.py',
      role: '테스트 페르소나 생성기',
    },
    {
      path: 'web-testing/research/scenarios.py',
      role: '페르소나 스와이프 시나리오 매핑',
    },
    {
      path: 'web-testing/run.py',
      role: 'E2E 테스트 러너 CLI',
    },
    {
      path: 'web-testing/runner/__init__.py',
      role: 'runner 패키지 init',
    },
    {
      path: 'web-testing/runner/collector.py',
      role: '테스트 실행 데이터 수집기',
    },
    {
      path: 'web-testing/runner/feedback.py',
      role: '구조화 피드백 생성기',
    },
    {
      path: 'web-testing/runner/reporter.py',
      role: '테스트 리포트 생성기',
    },
    {
      path: 'web-testing/runner/runner.py',
      role: 'Playwright E2E 실행 오케스트레이션',
    },
  ],
  systemFlow: {
    title: 'System Flow — Browser → Vercel → Django → DBs / external services',
    mermaid: `flowchart LR
  Browser["Browser"]
  Vercel["Vercel React<br/>frontend/src"]
  ApiClients["Frontend API clients<br/>frontend/src/api/{auth,sessions,projects,<br/>discovery,profiles,social,images}.js"]
  Django["Django backend<br/>backend/config/urls.py"]
  Apps["apps.accounts · apps.recommendation<br/>apps.profiles · apps.social"]
  Views["views/{sessions,swipe,search,projects,<br/>reports,discovery,telemetry}.py"]
  Engine["engine.py<br/>services/parse_query.py"]
  DefaultDB[("default DB · Neon<br/>User · Project · AnalysisSession · SwipeEvent")]
  BuildingsDB[("buildings DB · Neon<br/>canonical_v2_buildings (read-only raw SQL)")]
  Redis[("Redis cache (prod) · LocMemCache (local)<br/>JWT user-row cache · async prefetch · response cache")]
  Gemini["Gemini API"]
  R2["Cloudflare R2 image CDN"]
  OAuth["Google · Kakao · Naver OAuth"]

  Browser --> Vercel --> ApiClients --> Django --> Apps --> Views
  Views --> Engine
  Views --> DefaultDB
  Views --> Redis
  Engine --> BuildingsDB
  Engine --> Redis
  Engine --> Gemini
  Views --> OAuth
  Browser -. images .-> R2`,
  },
  recommendationFlow: {
    title: 'Recommendation / Swipe Flow — LLM parse → swipe loop → result',
    mermaid: `flowchart TD
  Search["LLMSearchPage.jsx"]
  ParseAPI["POST /api/v1/parse-query/<br/>ParseQueryView"]
  ParseSvc["services/parse_query.py<br/>Gemini chat · structured_filters<br/>visual_description"]
  SessionCreate["POST /api/v1/analysis/sessions/<br/>SessionCreateView"]
  SwipeUI["SwipePage.jsx"]
  SwipeAPI["POST /api/v1/analysis/sessions/&lt;id&gt;/swipes/<br/>SwipeView"]
  Engine["engine.py<br/>compute_mmr_next · farthest_point_from_pool<br/>refresh_pool_if_low · compute_taste_centroids"]
  RawSQL[("canonical_v2_buildings<br/>raw SQL · is_publishable=true")]
  ResultUI["ResultsPage.jsx"]
  ResultAPI["GET /api/v1/analysis/sessions/&lt;id&gt;/result/<br/>SessionResultView"]
  Reports["reports.py<br/>generate_report · generate_report_image"]

  Search --> ParseAPI --> ParseSvc --> SessionCreate
  SessionCreate --> SwipeUI
  SwipeUI --> SwipeAPI --> Engine --> RawSQL
  Engine --> SwipeUI
  SwipeUI -- converged --> ResultUI --> ResultAPI --> Engine
  ResultUI --> Reports`,
  },
  agentFlow: {
    title: 'Agent + Skill Flow — Main Session → orchestrate skill → skills + agents',
    mermaid: `flowchart LR
  Session["Main Session<br/>opus 4.7 · architecture · plan · dispatch"]
  Orchestrate["orchestrate skill<br/>feature implementation playbook"]
  BackMaker["back-maker · sonnet"]
  FrontMaker["front-maker · sonnet"]
  Review["code-review · sonnet"]
  Security["security-manager · sonnet"]
  GCommit["git-commit skill<br/>(replaces git-manager agent)"]
  AppTest["app-test · sonnet"]
  RInline["reporter-inline skill<br/>(replaces reporter agent;<br/>inline before squash)"]
  GPublish["git-publish skill<br/>(Mode 2; replaces git-publisher agent<br/>default routine path)"]
  GPubAgent["git-publisher · sonnet<br/>(Mode 3 deploy / triage / rebase only)"]

  Session --> Orchestrate
  Orchestrate --> BackMaker
  Orchestrate --> FrontMaker
  BackMaker --> Review
  FrontMaker --> Review
  Review --> Security
  Security --> GCommit
  GCommit --> AppTest
  AppTest --> GPublish
  GPublish --> RInline
  RInline --> GCommit
  GCommit -.-> GPublish
  GPublish -. escalate edge .-> GPubAgent`,
  },
  milestones: [
    {
      phase: '1–12',
      focus: 'Single-user reference exploration base (auth, 4-phase recommendation, Gemini search, persona report, project CRUD, E2E infra)',
      status: 'shipped',
    },
    {
      phase: '13',
      focus: 'Profile system — firm + user profiles, public/private boards',
      status: 'shipped',
    },
    {
      phase: '14',
      focus: 'Board system — board detail view, follow, "Love this!" reaction',
      status: 'shipped',
    },
    {
      phase: '15',
      focus: 'Social foundation — external DM links, MATCHED! results screen',
      status: 'shipped',
    },
    {
      phase: '16',
      focus: 'Recommendation expansion — Profile-tab office + user recs',
      status: 'pending',
    },
    {
      phase: '17',
      focus: 'LLM chat refinement — reverse-Q to fill required info slate (persona classification dropped)',
      status: 'pending',
    },
    {
      phase: '18',
      focus: 'External connections — firm article crawl (Space, ArchDaily, news)',
      status: 'pending',
    },
    {
      phase: '19–26',
      focus: 'Tab 3-structure replan + P1–P6 latency/UX overhaul',
      status: 'shipped',
    },
    {
      phase: 'design',
      focus: 'Design-system redesign — light-mode tokens, 4-theme switcher, frontend rework',
      status: 'in progress',
    },
  ],
};
