/*
 * project/state.js — ArchiTinder Make Web project state.
 *
 * Generated by the `reporter` agent at session end. Hand-edited only inside
 * `systemFlow` / `recommendationFlow` / `agentFlow` Mermaid bodies and the
 * `milestones` archive (semi-static), all other sections are rebuilt from
 * `.claude/Task.md`, `gh pr list`, and `.claude/agents/*.md` frontmatter.
 *
 * Loaded via <script> by `project/dashboard.html`, which opens by double-click
 * via file:// — no fetch, no server, no build step.
 *
 * Three-bucket model:
 *   - `done`      = resolved work (merged, shipped, archived)
 *   - `now`       = current initiative slice (one or more PRs in flight)
 *   - `next`      = backlog / planned / deferred work
 *
 * Time convention: all human-facing timestamps are `YYYY-MM-DD HH:mm KST`.
 * PRs additionally carry the raw `mergedAt` (ISO 8601 UTC from `gh pr list`)
 * so the value can be re-parsed by any consumer.
 */
window.PROJECT_STATE = {
  meta: {
    name: 'ArchiTinder — Make Web',
    updatedAt: '2026-05-24',
    head: 'fd063e0',
    branch: 'feature/admin-session-end-reporter-post-ci-fix',
  },

  done: [
    {
      id: 'DEPLOY-2026-05-24-v2',
      title: '#16 DEPLOY-2026-05-24-v2 — develop → main deploy, 1 PR (#97)',
      completedAt: '2026-05-24',
      prs: [98],
      note: 'Release PR #98 squash-merged CI hang fix to main (fd063e0). Railway deployment a98725bf Online. Bug #5 carve-out applied (develop force-reset to fd063e0). Prod functional pre-deploy (PR #94 cap working); this deploy = CI baseline alignment + main/develop sync.',
    },
    {
      id: 'CI-HANG-FIX',
      title: '#15 CI-HANG-FIX — _retry_gemini_call executor → daemon Thread + Queue',
      completedAt: '2026-05-24',
      prs: [97],
      note: 'ThreadPoolExecutor + future.result(timeout) → threading.Thread(daemon=True) + queue.Queue.get(timeout). _Thread captured at module-load to bypass test_imp8 _DiscThread global mock leak. Same 15s/45s deadline + FATAL + retry semantics. PR #94 ThreadPoolExecutor hung pytest CI 15min, cascading 5 CI failures. Full suite: 683 passed / 11 skipped / 0 failed.',
    },
    {
      id: 'GEMINI-TIMEOUT-CAP',
      title: '#13 GEMINI-TIMEOUT-CAP — hard 15s timeout cap on Gemini retry wrapper',
      completedAt: '2026-05-24',
      prs: [94],
      note: '_retry_gemini_call caps every Gemini SDK call at 15s (45s Imagen3) via ThreadPoolExecutor + future.result(timeout). 228s /parse-query/ hang → ≤31s. 4 new tests + 5 regression. Deferred: _caches.py:92 IMP-5 create call bypasses wrapper (context_caching_enabled default False, zero prod impact).',
    },
    {
      id: 'BUILDINGS-DB-SWAP',
      title: '#12 BUILDINGS-DB-SWAP — buildings DB neondb → archi_data + make_web role',
      completedAt: '2026-05-24',
      prs: [93],
      note: 'Make DB renamed buildings DB neondb → archi_data; new SELECT-only role make_web (was neondb_owner); canonical_v2_architects table added (14,216 firms). Make Web swapped .env + Railway prod env vars; refreshed .env.example + CLAUDE.md is_publishable stat (39/39,776 → 2,614/39,478 ~6.6%) + docs/database-schema.md. Prod redeploy 04e7633e Online verified.',
    },
    {
      id: 'V1-LEGACY-CLEANUP',
      title: '#11 V1-LEGACY-CLEANUP — drop architecture_vectors refs + orphan tables',
      completedAt: '2026-05-24',
      prs: [92],
      note: 'Neondb local-dev branch drop + 23 orphan user/app tables + legacy architecture_vectors dropped. 3 backend v1 files deleted (algorithm_tester.py, profile_image_latency.py, test_chat_phase_style_labels). 5 stale doc refs refreshed. Plan merry-toasting-dove.md archived.',
    },
    {
      id: 'DEPLOY-2026-05-24',
      title: 'develop → main deploy — 21 PRs (#68–#89)',
      completedAt: '2026-05-24',
      prs: [90],
      note: 'Release PR #90 squash-merged 21 PRs to main (179d6f6). Railway prod confirmed Online. origin/develop force-reset to match main (Bug #5 carve-out).',
    },
    {
      id: 'DASHBOARD-REWORK',
      title: 'Dashboard rework — 5-tab Done/Now/Next + Mermaid flows + KST timestamps',
      completedAt: '2026-05-24',
      prs: [89],
      note: '6-tab → 5-tab Done/Now/Next/System Flow/Agent Flow; mermaid.min.js vendored; Task.md sections renamed Open→Next / In Progress→Now / Resolved→Done; state.js schema rewritten; reporter.md spec updated.',
    },
    {
      id: 'CODEX-R2',
      title: 'Codex Round 2 audit — 7 findings resolved',
      completedAt: '2026-05-24',
      prs: [85, 86, 87],
      note: 'images/batch validation, BoardDetail normalize, useBoard decouple, SwipePage analyzing %, Gemini auth-error fail-fast, discovery taste-vector TTL cache',
    },
    {
      id: 'CODEX-EXT-9',
      title: 'External codex audit — 9 findings resolved',
      completedAt: '2026-05-23',
      prs: [81, 82, 83],
      note: 'raw_query dual-key, swipe idempotency full payload, Project row lock, DPP 3× overfetch, diverse RANDOM 2-query, ProjectList N+1, JWT blacklist, image_focus plumb, exploring bar 3→4',
    },
    {
      id: 'AUDIT-T3',
      title: 'Audit Tier 3 ops risk',
      completedAt: '2026-05-23',
      prs: [79],
      note: 'ORDER BY RANDOM 2-query, sync corpus-rank, GET-write atomic, thread-local telemetry',
    },
    {
      id: 'AUDIT-T2',
      title: 'Audit Tier 2 UX-contract bugs',
      completedAt: '2026-05-23',
      prs: [76, 77, 78],
      note: 'area filter normalize, FE→BE raw_query plumb, dead /matched route, rerank response shape, profiles legacy table',
    },
    {
      id: 'DEPLOY-PROD',
      title: 'Neon DB-split + production deploy',
      completedAt: '2026-05-22',
      prs: [63],
      note: 'app DB = user_data (57 migrations, 23 tables), buildings DB = neondb (39,776 rows); deploy 69c9473a verified healthy. (Buildings DB later renamed neondb → archi_data on 2026-05-24 by Make DB.)',
    },
  ],

  now: [
    {
      id: 'DESIGN-REWORK',
      title: 'Design-system redesign — per-component rework',
      startedAt: '2026-05-08',
      note: 'Foundation shipped (PR #54: tokens.css 4 themes + ThemeContext + AppearanceSettings). Remaining: per-component visual rework (~7,700 LOC, inline styles → CSS Modules + :hover, light-theme visuals) across the frontend, leaf→hub order. Scope with /plan per slice.',
    },
  ],

  next: [
    {
      id: 'AUTH1',
      title: 'Kakao / Naver OAuth',
      note: 'Google OAuth only today. Korean users need domestic login. Backend + frontend buttons for both.',
    },
    {
      id: 'AUDIT-T4',
      title: 'Audit Tier 4 — structural refactor (deferred)',
      note: 'File decomp: engine.py (2079 LOC), App.jsx (795 LOC), BoardDetailPage (1032 LOC), UserProfilePage (990 LOC), PostSwipeLandingPage (696 LOC), SwipePage (666 LOC), FirmProfilePage (611 LOC).',
    },
    {
      id: 'PHASE16',
      title: 'Phase 16 — Recommendation expansion (Profile-tab office + user recs)',
      note: 'Spec: docs/specs/phase16-recommendation-expansion.md. REC1 already executed as Push S3; REC2 / REC3 serve a Profile-tab "사무소 추천" button (Q3 decision); Landing tab deleted by Push S6.',
    },
    {
      id: 'PHASE17',
      title: 'Phase 17 — LLM reverse-questioning (pre-swipe persona classification)',
      note: 'Spec: docs/specs/phase17-llm-reverse-q.md. Reverse-question lives in the first 0-2 turns of the Taste-tab LLM chat. Per-persona UI branching for P1-P4.',
    },
    {
      id: 'PHASE18',
      title: 'Phase 18 — External connections (firm article crawl)',
      note: 'Spec: docs/specs/phase18-external-connections.md. Lower priority than Phase 16-17. Space, ArchDaily, news crawler + article list UI + external DM links.',
    },
  ],

  prs: [
    {
      number: 98,
      title: 'Release: 2026-05-24 — CI hang fix (PR #97)',
      mergedAt: '2026-05-24T10:58:47Z',
      mergedAtKST: '2026-05-24 19:58 KST',
    },
    {
      number: 97,
      title: 'fix(gemini): swap executor for daemon Thread + Queue (CI hang)',
      mergedAt: '2026-05-24T08:01:27Z',
      mergedAtKST: '2026-05-24 17:01 KST',
    },
    {
      number: 95,
      title: 'chore: session-end reporter housekeeping — PRs #92/#93/#94 + plan archive',
      mergedAt: '2026-05-24T04:30:44Z',
      mergedAtKST: '2026-05-24 13:30 KST',
    },
    {
      number: 94,
      title: 'fix(gemini): hard 15s timeout cap on retry wrapper (228s hang → ≤31s)',
      mergedAt: '2026-05-24T04:26:12Z',
      mergedAtKST: '2026-05-24 13:26 KST',
    },
    {
      number: 93,
      title: 'chore: buildings DB swap to archi_data + make_web role (config + docs)',
      mergedAt: '2026-05-24T03:19:05Z',
      mergedAtKST: '2026-05-24 12:19 KST',
    },
    {
      number: 92,
      title: 'chore: drop v1 architecture_vectors refs — 2 files + 4 doc fixes',
      mergedAt: '2026-05-24T01:42:39Z',
      mergedAtKST: '2026-05-24 10:42 KST',
    },
    {
      number: 91,
      title: 'chore: session-end reporter housekeeping — 2026-05-24 post-deploy',
      mergedAt: '2026-05-24T00:48:21Z',
      mergedAtKST: '2026-05-24 09:48 KST',
    },
    {
      number: 89,
      title: 'feat: dashboard rework — 5-tab Done/Now/Next + Mermaid flows + KST timestamps',
      mergedAt: '2026-05-23T16:58:28Z',
      mergedAtKST: '2026-05-24 01:58 KST',
    },
  ],

  agents: [
    {
      name: 'back-maker',
      role: 'Django/DRF backend code — only touches files inside backend/. Runs flake8 after changes.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'front-maker',
      role: 'React/Vite frontend code — only touches files inside frontend/. Runs ESLint after changes.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'code-review',
      role: 'Static code review — integration correctness, API contracts, logic bugs, error handling. Inner loop, per change, pre-commit.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'security-manager',
      role: 'Security scan — SQL injection, auth bypass, secret leakage, XSS, token storage. Inner loop, per change, pre-commit.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'app-test',
      role: 'Pre-push gate — live-browser 3-persona swipe journey + drift check. FULL or FEATURE-SCOPED mode.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'git-manager',
      role: 'Single commit — stages changed files (excluding secrets), writes caveman-terse conventional-commit message. Never pushes.',
      model: 'haiku',
      effort: 'default',
    },
    {
      name: 'git-publisher',
      role: 'Push + PR open/poll + squash merge + branch cleanup + develop→main deploy PRs. Never commits source code.',
      model: 'sonnet',
      effort: 'default',
    },
    {
      name: 'reporter',
      role: 'Session-end — updates Task.md, regenerates this dashboard state, conditionally syncs docs/algorithm.md.',
      model: 'sonnet',
      effort: 'default',
    },
  ],

  systemFlow: {
    title: 'System Flow — Browser → Vercel → Django → DBs / external services',
    mermaid: `flowchart LR
  Browser["Browser"]
  Vercel["Vercel React<br/>frontend/src"]
  ApiClients["Frontend API clients<br/>frontend/src/api/{auth,sessions,projects,<br/>discovery,profiles,social,images}.js"]
  Django["Django backend<br/>backend/config/urls.py"]
  Apps["apps.accounts · apps.recommendation<br/>apps.profiles · apps.social"]
  Views["views/{sessions,swipe,search,projects,<br/>reports,discovery,telemetry}.py"]
  Engine["engine.py<br/>services/parse_query.py"]
  DefaultDB[("default DB · Neon<br/>User · Project · AnalysisSession · SwipeEvent")]
  BuildingsDB[("buildings DB · Neon<br/>canonical_v2_buildings (read-only raw SQL)")]
  Gemini["Gemini API"]
  R2["Cloudflare R2 image CDN"]
  OAuth["Google · Kakao · Naver OAuth"]

  Browser --> Vercel --> ApiClients --> Django --> Apps --> Views
  Views --> Engine
  Views --> DefaultDB
  Engine --> BuildingsDB
  Engine --> Gemini
  Views --> OAuth
  Browser -. images .-> R2`,
  },

  recommendationFlow: {
    title: 'Recommendation / Swipe Flow — LLM parse → swipe loop → result',
    mermaid: `flowchart TD
  Search["LLMSearchPage.jsx"]
  ParseAPI["POST /api/v1/parse-query/<br/>ParseQueryView"]
  ParseSvc["services/parse_query.py<br/>Gemini chat · structured_filters<br/>visual_description"]
  SessionCreate["POST /api/v1/analysis/sessions/<br/>SessionCreateView"]
  SwipeUI["SwipePage.jsx"]
  SwipeAPI["POST /api/v1/analysis/sessions/&lt;id&gt;/swipes/<br/>SwipeView"]
  Engine["engine.py<br/>compute_mmr_next · farthest_point_from_pool<br/>refresh_pool_if_low · compute_taste_centroids"]
  RawSQL[("canonical_v2_buildings<br/>raw SQL · is_publishable=true")]
  ResultUI["ResultsPage.jsx"]
  ResultAPI["GET /api/v1/analysis/sessions/&lt;id&gt;/result/<br/>SessionResultView"]
  Reports["reports.py<br/>generate_report · generate_report_image"]

  Search --> ParseAPI --> ParseSvc --> SessionCreate
  SessionCreate --> SwipeUI
  SwipeUI --> SwipeAPI --> Engine --> RawSQL
  Engine --> SwipeUI
  SwipeUI -- converged --> ResultUI --> ResultAPI --> Engine
  ResultUI --> Reports`,
  },

  agentFlow: {
    title: 'Agent Flow — Main Session → orchestrate skill → 8 agents',
    mermaid: `flowchart LR
  Session["Main Session<br/>opus 4.7 · architecture · plan · dispatch"]
  Orchestrate["orchestrate skill<br/>feature implementation playbook"]
  BackMaker["back-maker · sonnet"]
  FrontMaker["front-maker · sonnet"]
  Review["code-review · sonnet"]
  Security["security-manager · sonnet"]
  GitMgr["git-manager · haiku"]
  AppTest["app-test · sonnet"]
  GitPub["git-publisher · sonnet"]
  Reporter["reporter · sonnet"]

  Session --> Orchestrate
  Orchestrate --> BackMaker
  Orchestrate --> FrontMaker
  BackMaker --> Review
  FrontMaker --> Review
  Review --> Security
  Security --> GitMgr
  GitMgr --> AppTest
  AppTest --> GitPub
  GitPub --> Reporter
  Reporter -. session-end .-> Session`,
  },

  milestones: [
    { phase: '1–12', focus: 'Single-user reference exploration base (auth, 4-phase recommendation, Gemini search, persona report, project CRUD, E2E infra)', status: 'shipped' },
    { phase: '13', focus: 'Profile system — firm + user profiles, public/private boards', status: 'shipped' },
    { phase: '14', focus: 'Board system — board detail view, follow, "Love this!" reaction', status: 'shipped' },
    { phase: '15', focus: 'Social foundation — external DM links, MATCHED! results screen', status: 'shipped' },
    { phase: '16', focus: 'Recommendation expansion — Profile-tab office + user recs', status: 'pending' },
    { phase: '17', focus: 'LLM reverse-questioning — pre-swipe persona classification', status: 'pending' },
    { phase: '18', focus: 'External connections — firm article crawl (Space, ArchDaily, news)', status: 'pending' },
    { phase: '19–26', focus: 'Tab 3-structure replan + P1–P6 latency/UX overhaul', status: 'shipped' },
    { phase: 'design', focus: 'Design-system redesign — light-mode tokens, 4-theme switcher, frontend rework', status: 'in progress' },
  ],
};
