# Generated by Django 4.2.30 on 2026-07-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='work',
            new_name='works_work_owner_i_cdca6c_idx',
            old_name='works_work_owner_i_idx',
        ),
    ]
