# Generated by Django 4.2.30 on 2026-08-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_rename_works_work_owner_i_idx_works_work_owner_i_cdca6c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='cover_r2_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
