# Generated by Django 4.2.30 on 2026-09-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_cover_r2_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='built_status',
            field=models.CharField(choices=[('built', 'Built'), ('unbuilt', 'Unbuilt')], default='built', max_length=10),
        ),
    ]
