# Generated by Django 4.2.29 on 2026-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_phase13_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font',
            field=models.CharField(choices=[('plex', 'IBM Plex Sans KR'), ('noto-serif', 'Noto Serif KR')], default='plex', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('github-light', 'GitHub Light'), ('github-dark', 'GitHub Dark'), ('ayu-light', 'Ayu Light'), ('synthwave-84', "SynthWave '84")], default='github-light', max_length=20),
        ),
    ]
