# Generated by Django 4.2.29 on 2026-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_liked_building_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English')], default='ko', max_length=5),
        ),
    ]
