# Generated by Django 4.2.29 on 2026-06-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
