# Generated by Django 4.2.29 on 2026-06-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_handle_userprofile_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
