# Generated by Django 4.2.30 on 2026-06-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_email_verified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following_count',
        ),
    ]
